### ISSUE TITLE
ZEVA - Separate transaction into different collapsable tables for each model year

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1257]
**Description**:
Due to the difficulty of how to display deficit balances in the current credit transaction and balance page, plus the growing list of transaction suppliers are building up, we want to redesign the credit transaction page:

IDIR - https://zeva-test.apps.silver.devops.gov.bc.ca/organizations/2/credit-transactions

BCeID - https://zeva-test.apps.silver.devops.gov.bc.ca/credit-transactions

As a result this will avoid the need to track the pay down of a credit deficit through out the compliance period. Instead the previous deficit will be taken in to account as part of the following years assessment.

**Tasks**
-separate transaction page into different tables/accordions for each compliance period/model year (new component)

(positive balance, accordians collapsed)
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/160942627?mode=fm

(positive balance, accordians expanded)
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/160856647?mode=fm

(previous compliance balance deficit)
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/161518599?mode=fm

These are all the possible deficit variations we need to account for.
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/159965397?mode=fm

**Acceptance Criteria**:
Given I am a ZEVA user (IDIR or BCeID)
When I am viewing the credit transactions page for an organization
Then I want to see the transactions broken down by compliance period
And the current credit balance shown separately at the top of the page

**Development Checklist**:
- create a reusable component for displaying transactions 
- rework transactions page to have the component display for each year

**Notes**:
Page should load with all accordians closed except the most recent/current compliance period one.

**Comment by kcabhar** [comment]
Comments from Jira:

James 23/Dec/22:
Page should load with all accordians closed except the most recent/current compliance period one.
