### ISSUE TITLE
ZEVA - ZEV sales not appearing in Nissan's model year report

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1269]
**Description:**
Nissan have been awarded credits for 188 sales of MY2021 ZEVs. The credits for these swere issued on 29th Sept 2022. The report was signed off and submitted on 19th October 2022.

These sales should appear in the second tab of their model year report, as they are doing for other suppliers. See the page at the location below.

https://zeroemissionvehicles.gov.bc.ca/compliance/reports/90/consumer-sales

Task is to investigate why Nissan''s ZEV sales are not appearing in their model year report and fix the issue if possible.

**Acceptance Criteria:**
Sales data from awarded credits should be visible in the second tab of the year report.

**Dev Checklist:**

- [ ] Verify if any anomalies in the Nissan's data which prevents the sales data to appear on the report.

- [ ] Compare Nissan's data with that of other suppliers to detect any abnormality and find a fix

**Comment by kcabhar** [comment]
Comments from Jira:

James 21/Dec/22:
Add other model year report bugs/issues to this card.

**Comment by tim738745** [comment]
Caused by incorrectly formatted data; fixed it in the production database; a card to be created to address the underlying issue
