### ISSUE TITLE
ZEVA - Credit transaction balance calculations

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1272]
**Description:**
On the page displaying the credit transaction for a supplier.

The balance column does not consistently or correctly keep track of the changes in the suppliers credits based on each transaction. This seems to be an issue when they are more than one transaction on the same day and/or when transaction are backdated to a date where there is already another credit transaction.

{see screenshot attached - redline}

**Task:**
Specify the order of each type of transaction (as Vihbi did in card 492 for the reassessment transaction).

**Expected Behaviour:**
The balance column displays the balance changes in the same order as the list of transactions, for all transactions including those on the same day.

Credit transactions that allocate credit should be shown before (below) those that reduce credits (above). See design attached by Al that includes all types of transactions (ct-order).

**Actual Behaviour:**
The balance column displays the balance changes out of order compared to the list of transactions, for transaction that are on the same day.

**Implications:**
The supplier may be confused as to how their current credit balance has been arrive at based on their individual credit transactions.

![ct-order.PNG](https://images.zenhubusercontent.com/637d5c007e28c84cebc3a147/4a75ef41-d546-4da8-b5aa-450ede17a64b)![Transaction balance.JPG](https://images.zenhubusercontent.com/637d5c007e28c84cebc3a147/a1c9e2b5-6a04-4835-84f5-cc450b7cd6a1)

**Comment by kcabhar** [comment]
**Comments from Jira:** 

Donald, James EMLI:EX added a comment - 21/Dec/22 11:34 AM
Points added in discussion with Alex but should be reviewed by wider dev team.

Ring, Alasdair I LWRS:EX added a comment - 21/Dec/22 2:01 PM - edited
Transactions that allocate credits and should be calculated first (on same day) are:
1. Automatic Administrative Penalty
2. Credit Applications
3. Initiative Agreements
4. Purchase Agreements
5. Administrative Credit Allocations

Transactions that can allocate or reduce credits are:
1. Credit Transfers

Transactions that reduce credits and should be calculated last (on same day) are:
1. Administrative Credit Reductions
2. Model Year Report Credit Reductions

**Comment by jdon-zev** [comment]
This should be super ceded by the re-working of the transaction page - card
