### ISSUE TITLE
ZEVA - Return Model Year Report to Supplier

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1276]
**Description:**
When the analyst returns a MY report to the supplier any changes made by the analyst in the change log or comments should be cleared.

As an analyst when I start assessing a report I may make edits and add comments to the report. I may then decide to return the report to the supplier.

Presently when I do this, the supplier makes changes and send the report back to government, the report retains the original updates and comments made by the analyst. These should not appear now that the supplier has re-submitted the report.

When returning the report to the supplier it would be best to discard any changes the analyst has made as part of this process.

**Acceptance Criteria:**
Given I am an idir user
When I return a model year report to the supplier
Then any analyst edits, assessment radio selection, and penalty number should be 'deleted'. Comments between analyst/director can be retained.

**Development Checklist:**
add boolean fields to model_year_report_assessment_comment, model_year_report_assessment, model_year_report_make , model_year_report_ldv_sales
mark these records as display=false (or whatever the field is called) when the analyst returns to supplier
ensure that any viewsets using those tables does not display records that are display=false
update the changelog logic so it takes into account that there could be extra records rather than just 2 (ie filter out display=false before doing anything else) or preferably filter out on the backend

**Notes:**

**Comment by kcabhar** [comment]
**James - 07/Sep/22**
Note - we decided to soft retain the previous information.

**Kimia- 12/Jan/23**
Following a discussion between James, Al and Kimia, this is card is to be done but in conjunction with a separate card to expand the report history to include a record of any report that is returned/sent back to a supplier.

**Comment by shayjeff** [comment]
The LDV sales submitted by the analyst did not clear out. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek95QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d0044b1f52330cee1b7082a1cacd2998088369b/image.png)

**Comment by shayjeff** [comment]
Everything is working as should except the comments between the analyst and the director are not being retained.  This is the only thing that should remain for the IDIR users. The PAC MY 2022 report shows the comments missing when the report was resubmitted by the supplier.
