### ISSUE TITLE
ZEVA - Review and Implement Static Data Storage for Supplier Submitted Data

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1278]
**Describe the task**
Currently, warnings in credit applications are being calculated using the latest ICBC data, which is not accurate as warnings should be calculated at the time of submission. To improve accuracy, we need to review the storage of warnings and credit submission data, and find a way to save the original warnings and any other supplier submitted data to the database.

**Purpose**
By making warnings and credit submission data static and stored to the database, we can increase the accuracy of the information that ZEVA provides.

**Acceptance Criteria**
- [ ] Investigate how credit applications store data, especially warnings for each VIN.
- [ ] Devise a way to store static snapshots of currently calculated data.
- [ ] Create a follow-up ticket that outlines new database tables, any required data migration, and an implementation plan for the changes.

**Additional context**
- The static vs. calculated data discussion has been previously discussed, so discussing with James and Al would provide more context.

**Comment by kcabhar** [comment]
Investigation and fix of an issue that was brought to light in ZEVA 1277

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1278?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by tim738745** [comment]
Each supplier-submitted VIN (an instance of the SalesSubmissionContent model) has an update timestamp associated with it. This timestamp is initially the time the supplier submits their application, but when an analyst clicks “verify with icbc data”, it gets changed to the time the analyst makes the click.
 
In response to the click and after the timestamp update, the system looks for the same ICBC VIN with an upload date before this timestamp (see the raw sql in the icbc_verification() function in …/models/sales_submission_content).
 
For example, suppose a supplier submits VIN 1234 on 2023-01-01, and, at this time, this VIN does not exist in the icbc data. Then, two months later, on 2023-03-02, the analyst clicks “verify with icbc data”; the most recent icbc data (suppose one uploaded on 2023-03-01) will be used, and if VIN 1234 exists in that most recent upload, then there will not be a “NO_ICBC_MATCH” warning.
 
So if the concern is that warnings are not being displayed when they should be, I think we can simply use the “create_timestamp” of the supplier-submitted VIN when grabbing the icbc data. If we did this, then, in the example above, the analyst would get a “NO_ICBC_MATCH” warning.
 
On the other hand, if we still wanted to derive warnings at the time of submission and save them in the database, we can; some implementation notes:
 
(1)   Pull the icbc_verification function out of the model and into a service module.
(2)   Create a new db table to store warnings (some columns may include: sales_submission_content_id, warning_type, icbc_upload_date_id, etc).
(3)   When a supplier submits a credit application, call the function mentioned in (1) and save the warnings to the table mentioned in (2).
(4)   Display these warnings to the analyst; the analyst should still have the option to verify with the latest ICBC data?
(5)   Of course, new models, serializers, viewsets, frontend changes, etc. will have to be made. Probably an 8 to do all this.

**Comment by tim738745** [comment]
See associated card #1469
