### ISSUE TITLE
ZEVA - Delete rejected/returned ZEV Model

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1285]
***Title:**
Enable BCeID \ ZEVA User to delete rejected or returned ZEV models so they can keep their list of ZEV manageable. Deleted ZEV are still visible to IDIR users.

***Description:***
If a ZEV model is rejected by government I can't do anything further with this record. I have to submit a new ZEV model if I need to change anything. Once I do that there is no purpose to keep the rejected record so I'd like to delete it if I so choose. 

If a ZEV model is returned by government as Changes Requested status I'd like the option to delete it if I so choose.

Add a Delete button to the ZEV model screen when in Rejected or Changes Requested statuses as per wireframe.

***Wireframe:***
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/131174652?mode=fm

***Purpose and benefit to user:***
Rejected ZEV model records serve no long term purpose and I'd like the choice to delete them.

***Acceptance Criteria:***

[] Given I am a BCeID Zeva user, When I have a zev model rejected by government, then I want to have the option to delete that model. 
[] Given I am an IDIR analyst, When a supplier deletes a rejected zev model, then I still want to be able to see the rejected zev model and its details. 

*Development Checklist:*
[] Add a delete button that's visible to suppliers when they are viewing an individual ZEV model.
[] Make it so that when the button is clicked, the associated ZEV model is given a "Deleted" status in the database.
[] Implement logic that makes it so that IDIR users can still see "Deleted" ZEV models, but BCeID users can't.

***Notes:***
Deleted ZEV are not deleted from the database and are still visible to IDIR users in Deleted status.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1285?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1285?planning-poker) with Zenhub @JulianForeman

**Comment by airinggov** [comment]
It doesn't appear the last dev checklist item is working, IDIR users cannot see deleted ZEV
