### ISSUE TITLE
ZEVA - Add a document attachment when processing a credit application

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1286]
**Title:**
Enable the IDIR analyst to attach documents to a credit application.

**Description:**
Presently the supplier can upload sales evidence documents as attachments when submitting a credit application. If the analyst has processed the application but then receives additional documents from supplier (the Director may have asked for further evidence) there is no way to add these documents as part of the permanent record. The CA has to be rejected and the supplier would have to re-submit ensuring all new attachments are included. This is a lot of additional work to both parties.

**Wireframe:** follow red arrows
https://preview.uxpin.com/246954456c24001734137c07f930e2a511a1d7c6#/pages/138264889?mode=fm
https://preview.uxpin.com/246954456c24001734137c07f930e2a511a1d7c6#/pages/160425457?mode=fm

**Purpose and benefit to user:**
The IDIR analyst can attach additional documents received after the CA was submitted to include them as part of the permanent record.

**Acceptance Criteria:**

-  Given I am a IDIR analyst, When I am reviewing a credit application, then I want to be able to upload documents to that application and I want these to be retained as part of the permanent transaction. 
-  Given I am a BCEID user, When I am click on a credit transaction, then I want to be able to view any documents attached to that transaction. 

**Development Checklist:**

- [ ] Add a functionality to attach additional documents to the Credit Application page for the IDIR analyst.
- [ ] Create a server-side API endpoint for uploading documents as well.
- [ ] Allow BCEID users to view the attached documents when they are viewing the credit application.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1286?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1286?planning-poker) with Zenhub @JulianForeman

**Comment by tim738745** [comment]
@airinggov the uxpin links in this card don't work; they lead to a "This prototype has gone down" page; could you please provide new wireframes?
