### ISSUE TITLE
DevOps - ZEVA - Change the storage of uploaded files from Openshift PVC to Object Storage

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1298]
The uploaded Zeva file size is over 700M sometime. We should consider either removing the file after it is stored in database or change the storage to Object Storage. No code change should be expected.

Consider to use the storage service from common service or the object storage directly

**Comment by kuanfandevops** [comment]
Currently TFRS uploads the files through Minio and store them on Openshift PVC. We will remove Minio and upload the files to Object Storage. The same protocol S3 is used, some help may be needed from developers to verify if CORS will be an issue for object storage.

**Comment by kuanfandevops** [comment]
Currently TFRS uploads the files through Minio and store them on Openshift PVC. We will remove Minio and upload the files to Object Storage. The same protocol S3 is used, some help may be needed from developers to verify if CORS will be an issue for object storage.
