### ISSUE TITLE
ZEVA - Bug -Model Year Report Assessment Calculation

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1302]
**Describe the Bug**
The math is wrong on the model year report assessment likely due to decimal places and rounding issues.

**Expected Behaviour**
Only 2 decimal places are displayed and should ever be used in calculations.

**Actual Behaviour**
It appears the calculations are being made with more than 2 decimal places then the result is being rounded. This will not normally be an issue but in some cases will display a value .01 off the correct value. As a result what is displayed is incorrect.

see screen capture below:
1,589.58 - 1,029.42 – 428.50 = 131.65 (should be 131.66)

**Implications**
A clear and concise description of any implications.

**Steps To Reproduce**
Steps to reproduce the behaviour:
see screen capture as this is very difficult to reproduce

**To do:**
calculate using the already rounded numbers

**Comment by airinggov** [comment]
![myra-bug.PNG](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/e1eb8990-6e39-4c1c-945d-76d9cde46d40)

**Comment by emi-hi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1302?planning-poker) with Zenhub @emi-hi @JulianForeman @jig-patel @tim738745 @AlexZorkin @vibhiquartech
