### ISSUE TITLE
ZEVA - Bug -  MY Report status message error

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1306]
**Describe the Bug**
The status messages on the first 4 tabs/pages of a model year report are being updated with incorrect user information.

**Expected Behaviour**
The message 'Model year report submitted Oct. 2, 2020 by Buzz Collins." should not change.

**Actual Behaviour**
The message 'Model year report submitted Oct. 2, 2020 by Buzz Collins." is being updated with government user name (analyst) in error when the report is recommended.

Suggest we remove the problem statement from the following 3 tabs/pages status as per screens attached. 
- Supplier Information
- Consumer ZEV Sales
- Compliance Obligation

The Summary page needs to be fixed to not change supplier information to analyst information when it is recommended.

**Implications**
Incorrect and confusing information is being displayed.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR analyst/director
1. Go to a MY report
2. Go through process of recommending
3. See status message change bceid user info to idir user info

**Acceptance Criteria:**

- [ ] Given I am a IDIR analyst/director

- [ ] When the status is changed

- [ ] The updated status message should not be changed.

**Development Checklist:**

- [ ] Remove the statements from these pages:
      - Supplier Information
      - Consumer ZEV Sales
      - Compliance Obligation

- [ ] Check My report status message doesn't get changed from the supplier info to the analyst info when the status is changed to recommended.

**Comment by airinggov** [comment]
I will add screen captures once I can get onto ZEVA test

**Comment by airinggov** [comment]
![myr-si-i.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/8e8fbfaf-76b6-4c3f-b2fb-bbe0fa74c64b)![myr-czs-1.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/c49d19e3-3b16-4f0b-a00d-533b803c2d21)![myr-co-i.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/8779da03-f505-4df3-a62d-d84f6cfb0b77)

**Comment by airinggov** [comment]
fix this status message so it doesn't get changed from the supplier info to the analyst info when recommende![myr-sum-i.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/32aa5d6a-42d3-44eb-afac-1e5052f8912c)![myr-sum-i-error.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/946c90a3-0c28-4c46-bc43-6666ae5b5e32)d

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1306?planning-poker) with Zenhub @AlexZorkin

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1306?planning-poker) with Zenhub @JulianForeman

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1306?planning-poker) with Zenhub @emi-hi

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1306?planning-poker) with Zenhub @vibhiquartech

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1306?planning-poker) with Zenhub @tim738745
