### ISSUE TITLE
ZEVA - ICBC Data Upload

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1312]
**Description:**

The ICBC data parsing is failing due to the size of the data file. To solve this we need to change how the parsing works to avoid processing data that isn't needed.

There were two rounds of memory optimizations that were unsuccessful in allowing the test environment to process the large files. We should look at creating a pre-processing endpoint that filters the un-needed elements from the data file before uploading to minio.

The November and December monthly data files are now available and have been uploaded to Teams.

**Acceptance Criteria:**

Pre-process data file to reduce the file size before uploading to minio (most likely on the backend and then pipe the processed file over to minio)
ICBC data uploads successfully every time.

**Development Checklist:**

Drop any registration that is model year 2018 or older
Filter out non-ev vehicles from the data

**Comment by AlexZorkin** [comment]
Files have been processed for 2022-11-30 and 2022-12-31. The files are located in the Zelda teams files folder.
