### ISSUE TITLE
ZEVA - Auth peice for gold migration

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1314]
Upgrade ZEVA Auth libraries to work with new gold standard realm.

Alex to complete card description.

**Comment by AlexZorkin** [comment]
Fixed issue with credit transfer aggregate method.

**Comment by jdon-zev** [comment]
Notes on page error issues:
From home page on Test, logged in as IDIR. Clicked to view a credit transfer (CT257 or CT250). I get we're sorry error message. After refresh get redirected to log-in screen but I'm not logged out. (Alex has now resolved this)
