### ISSUE TITLE
ZEVA - Display credit application history information to IDIR

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1324]
**Title:** Display credit application history information to IDIR

**Description:** The status information displayed to IDIR staff only provides the latest action. The BCeID status includes a history of the Excel upload and when it was saved and submitted to government. We'd like to display this info on the IDIR side as well.

**Wireframe:**
![8b890e7f-7fd7-4270-8de0-f30f9bc5fcbe.png](https://images.zenhubusercontent.com/6137e069d4b4d4743ef67430/ec760af7-42e3-45bd-a0b2-3d9d06061751)

**Purpose and benefit to user:** It is important to government to retain the info of when the CA was submitted

**Acceptance Criteria:**

- [ ] Given I am a government user when I am viewing a credit application, then I should see the history displayed below the status.

**Development Checklist:**
- [ ] Make sure credit history is uniform on BCeID side and IDIR side.
- [ ] Ensure existing credit applications are updated to pull and include the history information.

**Notes:**

**Comment by airinggov** [comment]
![ca-history.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/8b890e7f-7fd7-4270-8de0-f30f9bc5fcbe)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1324?planning-poker) with Zenhub @AlexZorkin @emi-hi @tim738745 @vibhiquartech @jig-patel @JulianForeman

**Comment by jdon-zev** [comment]
The intention here was that IDIR users should see the history in all relevant status. Currently it is only showing when the credit application is in 'Issued' and 'Rejected' statuses.
Please make the history also visible in these statuses: Submitted, Validated and Recommend Issuance.
