### ISSUE TITLE
ZEVA - BCeID supplementary report refinements

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1337]
**Description:**
The following issues were identified during testing of the yet to be released supplementary report feature.

1. For BCeID ZEVA user the re-assessment tab should be grey out, and there should be no hover over-message.
2. The value 'null' should not appear in the text areas (address field for example) of the supplementary report or reassessment. These are appearing  because there is not info in that field. (see screenshot in comment)

**Purpose and benefit to user:**
The benefit to the user is consistency with how reporting works in other areas of the app.

**Acceptance Criteria:**

1. Given I am a BceID ZEVA user, When I am drafting or reviewing a submitted supplementary report, then the re-assessment tab on the page should be greyed out and there should be no hover over message, until a reassessment has been issued by government.
2. Given I am a BceID ZEVA user, When I am drafting or reviewing a submitted supplementary report, or reviewing a reassessment, any values that are 'null' should not be shown in text areas.  

**Development Checklist:**
- [ ] Remove the hover text on the re-assessment tab for BCeID users by checking if user !isGovernment
- [ ] Make sure null values are display as '' empty strings rather than 'null' on the supplementary report or reassessment views.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1337?planning-poker) with Zenhub @emi-hi @tim738745 @vibhiquartech @jig-patel @JulianForeman

**Comment by jdon-zev** [comment]
![Null null null.JPG](https://images.zenhubusercontent.com/63c843041aa7297691df71de/fcd04ee1-1216-464e-810c-aef4c64ac847)
