### ISSUE TITLE
ZEVA - BCeID user unable to access their report once a reassessment is issued

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1338]
**Describe the Bug**
For a BCeID user, when they have been issued a reassessment by government they can no linger access their associated supplementary report anymore - the link to the page appears to be being changed.

**Expected Behaviour**
A BCEID ZEVA user should always be able to access a supplementary report that they have created.

**Actual Behaviour**
The BCeID ZEVA user cannot access their supplementary report after a reassessment has been issued.

**Implications**
The BCeID user is denied access to important information in the app that they should have access to.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID ZEVA User

1. After government has issued a reassessment to a supplier
2. Go to Compliance Reporting
3. Click on Reassessment and then click on the tab to view the supplementary report
3. See that you are unable to view the supplementary report.

**Acceptance Criteria**
Given that I am a BCeID user, when I am issued a reassessment, then I should still be able to view the supplementary report associated with the reassessment.

**Development Checklist**
(1) Maybe a fronted issue; see SupplementaryContainer.js first

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1338?planning-poker) with Zenhub @jig-patel

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1338?planning-poker) with Zenhub @emi-hi @AlexZorkin

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1338?planning-poker) with Zenhub @vibhiquartech @tim738745

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1338?planning-poker) with Zenhub @JulianForeman
