### ISSUE TITLE
ZEVA - Reassessment radio button selection fails to save on first try

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1340]
**Description:**
When the IDIR analyst role clicks to select a radio button at the bottom of the reassessment page, and then tries to save their selection, it fails to save on the first try.

**Purpose and benefit to user:**
The user needs to be able to save the radio button selection they have chosen so that they can recommend the supplementary report to the Director with a valid radio button selection.

**Acceptance Criteria:**
- Given I am an IDIR analyst, When I am choosing a radio button selection on the reassessment page, and then I click to save the reassessment, then the page should save every time including my radio button selection.

**Development Checklist:**
- [ ] Check what happens when a user clicks the save button for the first time; is the correct data being sent to the backend?
- [ ] If not, probably a frontend issue (the data stored in the state, or something wrong with handleSubmit(), etc.). If it is, then probably a backend processing issue.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1340?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
