### ISSUE TITLE
ZEVA - Re-assessment page format

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1351]
**Description:**
The 3rd tab which shows the reassessment page that is issued to the supplier should also be in its non editable format. Currently it is the same as the second tab, 'reassessment recommendation' until it is issued by the Director.

the first and second tabs should be the editable format

**Wireframe:** https://preview.uxpin.com/ba292bb89debd007a79659b3f657c3649ade8efa#/pages/144399377?mode=fm

**Purpose and benefit to user:**
The gov users, analyst and Director wants to be able to see exactly what will be issued to the supplier throughout the process of preparing, reviewing, recommending and issuing the re-assessment to avoid any uncertainty around what the supplier will be issued.

**Acceptance Criteria:**
- Given I am a gov analyst, when I am viewing a re-assesment the second tabs, "reassessment' should always display the reassessment in the editable format that will be sent to the director.
- Given I am a gov analyst or director, when I am viewing a re-assesment the third tab, "reassessment' should always display the reassessment in the non editable format that will be issued to the supplier.

**Development Checklist:**
- [ ] update first and second tabs to be in 'editable format'
- [ ] update third tab to be in 'final format'

**Notes:**

**Comment by emi-hi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1351?planning-poker) with Zenhub @AlexZorkin @tim738745 @emi-hi @vibhiquartech
