### ISSUE TITLE
ZEVA - Grey out and re-name supplementary details tab when no supplementary report exists

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1352]
**Description:**
For consistency with other areas of the app, if government initiates a re-assessment where there is no supplementary report, then the supplementary details tab should be greyed out. supplementary details should be grey out if there is no supplementary report

Also the supplementary details tab should be renamed to be Supplementary Report. Please re-name.

**Purpose and benefit to user:**
This change will provide clarity and consistency for IDIR users on whether a supplementary report has been submitted in relation to this reassessment.

**Acceptance Criteria:**
- Given I am a an IDIR user, when I initiate a reassessment and there is no associated supplementary report, then the first tab, which should be named Supplementary report, should be greyed out and there should be no hover over text on it.

**Development Checklist:**
- [ ] A. Rename supplementary details tab to Supplementary Report.
- [ ] B.  Make Supplementary Report greyed out, if there is no supplementary report during re-assessment and also remove the hover over text on it.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1352?planning-poker) with Zenhub @AlexZorkin @emi-hi @tim738745 @vibhiquartech
