### ISSUE TITLE
ZEVA - Supplemental report and reassessment consistency issues

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1354]
**Description:**
There are a two consistency issues with supplemental reports and reassessments that need to be cleaned up. They are listed below.

- Some changes made by the BCeID or IDIR users to credit value then result in updating calculations automatically (like when LDV sales value is changes) but others don't update until you save the page. It would be better if any change in value that changes other values updated automatically.
- On the BCeID side - changes to credits values made by the user do not all highlight yellow, only the one you typed is highlighted. It woudl be helpful if all values that change highlight yellow.

Specific example - when an IDIR user updates the 'credits issued for consumer sales' the corresponding 'balance before credit reduction' and 'Assessed balance' did not update until the reassessment was saved again.

**Purpose and benefit to user:**
Consistency helps provide users with certainty on what is happening on the page when they make changes to values.

**Acceptance Criteria:**
- [ ] Given I am a BCeID or IDIR user, When I am updating credit values on a supplemental or reassessment, then all calculated fields update automatically on the page 
- [ ] Given I am a BCeID user, When I am updating inputs fields on a supplemental or reassessment report, then all changed fields get highlighted in yellow

**Development Checklist:**
- [ ] Make all input fields re-calculate 'on the fly' rather than having to save the page before seeing the updated values.
- [ ] Update all changed fields to be highlighted in yellow.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1354?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
