### ISSUE TITLE
ZEVA - IDIR user cannot view supplementary report tab

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1355]
**Describe the Bug**
For IDIR users they are unable to view the supplementary details tab after the reassessment is issued by government. If this exists it should be available for IDIR users to view as a locked snapshot. In the instance where there was no supplementary report because the reassessment was initiated by government then the supp details tab should be greyed out to show it does not exist.

**Expected Behaviour**
IDR user should always be able to click to view the supplementary report details if  a supplier has submitted a supplementary report, even after a resulting reassessment has been issued.

**Actual Behaviour**
When the IDIR user tries to view the supp report tab, after a re-assessment has been issued, they can't click on it and a hover over message appears that says no supp report found.

**Implications**
A clear and concise description of any implications.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Go to issued reassessment
2. Try to click on supplementary details tab

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1355?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by kcabhar** [comment]
This may already be resolved
