### ISSUE TITLE
ZEVA - Make ZEV Models Active=Yes,- the default display 

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1356]
**Title:** Make ZEV Models Active=Yes,- the default display on the ZEV Models page, both BCeID and IDIR

**Description:** Suppliers can make ZEV models inactive if they are no longer being sold. This keeps the ZEV Model page list more manageable (and also removes them from the credit application excel template). The filter on the Action Yes/No column should default to Yes. Even when the Clear Filters button is clicked it should keep the Yes filter. Users can click the Show Inactive ZEV button to change the filter to No (and of course they can also type Yes or No).

The dash is also required to see models that are in Draft, Submitted and Changes Requested statuses

This change should be done for all BCeID and IDIR users/roles.

**Wireframe:** https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/131174642?mode=fm

**Purpose and benefit to user:** It keeps the page display more manageable as was intended by this feature.

**Acceptance Criteria:**

- [ ] Given I am a BCeID or IDIR user, When I am looking at the ZEV Models List page, then the default view filters out Inactive ZEV.

**Development Checklist:**
- [ ] Update so when the VehicleListTable displays, it always defaults to filtering out the inactive models when the page loads
- [ ] The only time the inactive models should appear is if 'show inactive models' button is clicked or if 'no' is typed in the column filter
- [ ] When 'clear filters' button is pressed, reset all filters except set the active filter to not show inactive models. If they want to clear all filters except the active/inactive models, they will need to manually type no in that column

**Notes:**

**Comment by emi-hi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1356?planning-poker) with Zenhub @AlexZorkin @emi-hi @JulianForeman @tim738745 @vibhiquartech

**Comment by airinggov** [comment]
I updated this card to add information about the default filter needs to include a dash (Yes,-) so the points of the card may need altered from 3

**Comment by airinggov** [comment]
The filter isn't including the -/dash. This is an issue as it doesn't display ZEV in draft, submitted, rejected status that are neither Active Yes or No. Filtering used to support multiple values separated by a comma but it doesn't appear to work now.
