### ISSUE TITLE
ZEVA - BUG - BCeID dashboard, broken link for Credit Agreements

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1357]
**Describe the Bug**
The BCeID dashboard alert for Credit Agreements links to the Credit Agreements page which is only available on the IDIR side. The link can be updated to link to the main Credit Balance/Credit Transactions page as that is where they are displayed.
https://zeva-test.apps.silver.devops.gov.bc.ca/credit-transactions

**Expected Behaviour**
The BCeID dashboard alert for "Credit Agreements - # recorded by the Government of B.C." should link to
https://zeva-test.apps.silver.devops.gov.bc.ca/credit-transactions

no filters or parameters are required.

**Actual Behaviour**
Presently it links to
https://zeva-test.apps.silver.devops.gov.bc.ca/credit-agreements?col-status=Issued

which is wrong on the BCeID side 

**Implications**
A clear and concise description of any implications.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Go to dashboard as BCEID
2. Click on credit agreement alert (need to have some recorded)

**Comment by emi-hi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1357?planning-poker) with Zenhub @tim738745 @AlexZorkin @JulianForeman @vibhiquartech @emi-hi

**Comment by jdon-zev** [comment]
The link now re-directs the BCeID user to the credit transaction page but the page information does not load. All they see is a blank page.

**Comment by shayjeff** [comment]
Credit agreement is opening to the credit transfers URL, when it should be opening to the credit transactions page.
