### ISSUE TITLE
ZEVA - Remove Supplementary tab from Reassessments when there is no supplementary report

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1363]
**Title:** Remove Supplementary tab from Reassessments when there is no supplementary report

**Description:** If government has created a reassessment, and there is no associated supplementary report for the supplier, then only 2 tabs should be visible. The Reassessment Recommendation tab and the Reassessment tab. Currently the user still sees the Supplementary Report tab.

**Wireframe:** <https://preview.uxpin.com/ba292bb89debd007a79659b3f657c3649ade8efa#/pages/144446488?mode=fm>

**Purpose and benefit to user:**
Reducing confusion to the user about whether a reassessment has an associated supplementary report or not.

**Acceptance Criteria:**
- Given I am a gov analyst/director, When I am reviewing a reassessment, and there is no associated supplementary report from the supplier, then the supplementary report tab should not be visible,

**Development Checklist:**
- [ ] add a condition on the frontend for if a supplementary report exists. If it does not do not show the tab 

**Notes:**

**Comment by emi-hi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1363?planning-poker) with Zenhub @AlexZorkin @jig-patel @JulianForeman @vibhiquartech @emi-hi
