### ISSUE TITLE
ZEVA - allow Zero value in model year LDV Sales field

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1364]
**Title:** Allow a Zero value to be entered in the model year LDV Sales input in Model Year Reports and Supplementary / Reassessment reports.

**Description:** Currently if a user enters a zero in the field - [Year] Model year LDV sales - in the supplementary report or reassessment recommendation pages it will thrown an error. But we would like the it to be possible to enter a zero value in this field. 

**Purpose and benefit to user:**
The user will not experience an error if they enter a zero value in this field.

**Acceptance Criteria:**
- [ ] Given I am a ZEVA User or government analyst, When I am working on a supplementary report or reassessment recommendation, then I want to be able to enter a zero value in the [Year] Model year LDV sales field.

**Development Checklist:**
- [ ] Allow 0 float value as a valid save object. Check if there is code that replaces 0 with null or validation that doesn't accept 0 in this field. 
- [ ] Ensure that saving a 0 value updates the calculated credit values below in the form and saves those changes when submitted.

**Notes:**
![image.png](https://images.zenhubusercontent.com/63c843041aa7297691df71de/e246a659-8abc-4104-9051-50619f322a9d)

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1364?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
