### ISSUE TITLE
ZEVA - Add ability to edit comments (in-situ comment feature) in Reassessment Recommendation tab between the analyst/director

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1365]
**Title:**  Add ability to edit comments (in-situ comment feature) in Reassessment Recommendation tab between the analyst/director.

**Description:**
Currently it is not possible for IDIR user to edit the comment they add to the Reassessment Recommendation tab. As in other areas of the app that have comment features, such as Assessments and credit applications, the user would like to be able to edit their own comments.

**Purpose and benefit to user:**
Comments can be updated and error corrected after comments have been added.

**Acceptance Criteria:**
- Given I am a government analyst or director, When I am adding comments, then I want to be able to edit comments I have added.

**Development Checklist:**
- [ ] Swap out the comments component being used in the reassessment/supplementary views for the one in credit applications that supports editing in place of comments.
- [ ] This may require removal of the comment api calls from the supplementary container component in favour of the calls in the child component so make a plan before starting this work.

**Notes:**
Chat with Alex or Tim first who worked on these editable components.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1365?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1365?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by airinggov** [comment]
received We're sorry error when saving edited comment

**Comment by tim738745** [comment]
@airinggov On test, it appears that it can't find the new backend endpoint for updating edited comments; can't seem to recreate this locally; will talk with Alex/Kuan to see if something went wrong with the build/deployment

**Comment by tim738745** [comment]
@airinggov Kuan just reran the test deployment; should be working now

**Comment by airinggov** [comment]
@tim738745 It's working, looks great, thanks Tim. I will close the card
