### ISSUE TITLE
ZEVA - Disable Add Comment button on draft Reassessment Recommendation until page is saved

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1366]
**Title:** Disable Add Comment button on draft Reassessment Recommendation until page is saved

**Description:** When the IDIR government analyst user clicks to create a Reassessment Recommendation, the page that opens is not saved so nothing actually exists and when the user clicks the Add Comment button it throws an error page.

Solution - Disable the comment text area and the Add Comment button until the page has been saved once. Disable by greying them out. Add hover text to the disabled button "Please save before adding a comment".

Note, this comment feature is being changed to the in situ comment feature with comment editing. Card 1365.

**Purpose and benefit to user:**
The user will no longer get a page error when they try to enter a comment.

**Acceptance Criteria:**
- Given I am a government user, When I am preparing a reassessment recommendation, I want the Add Comment button and comment text feature to be disabled (greyed out), and a hover message appear if I try to click on it, until I save the page. 

**Development Checklist:**
- [x] A. On load of Reassessment Recommendation page make the Add Comment button disable until the page is saved.
- [x] B. Make the required changes on the frontend to make the Button Disable so that it will not throw any error page.
- [x] C. Also grey out the comment text feature.

**Notes:**

**Comment by jdon-zev** [comment]
![Disable comment feautre.JPG](https://images.zenhubusercontent.com/63c843041aa7297691df71de/6937632e-7965-4f50-877a-93302c557bcf)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1366?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
