### ISSUE TITLE
ZEVA - Disable editing opening credit balances

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1367]
**Title:** Supplementary Reports and Reassessment Recommendations should not allow editing the Opening Credit Balance ever.

**Description:**
Remove the ability for all users to edit the starting credit balance - 'CREDIT BALANCE AT END OF SEPT. 30, [Year]'. This is not a field that anyone should be able to edit.
The only way an opening balance can be changed is by having the previous year report reassessed. Any new closing balance resulting form that reassessment is used as the starting balance for the following years reports/assessments.

**Purpose and benefit to user:**
This will avoid the opening and closing credits balances of a supplier in consecutive years from being out of sync.

**Acceptance Criteria:**
- Given I am a ZEVA user or government analyst, When I am preparing a supplementary report or a reassessment, then I should not be able to edit the field - CREDIT BALANCE AT END OF SEPT. 30, [Year]

**Development Checklist:**
- [ ] Make the credit balance at end of sept. 30 Field not editable by setting disabled={true}
- [ ] May want to remove any existing logic around editing/saving changes to this field

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1367?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
