### ISSUE TITLE
ZEVA - Reassessment tab format and availability

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1368]
**Title:** Make Reassessment tab available to view before being reassessed and in the final format

**Description:** As an IDIR analyst the reassessment tab should be viewable at all times and statuses (after Save). The format of this page should always be the final (non-editable) format.

Presently this format is only displayed after the Director Issues the Reassessment.

**Purpose and benefit to user:**
Clarity to the user of what they are recommending to the Director (in terms of format and content).

**Acceptance Criteria:**
- Given I am a gov analyst, when I am working on a reassessment recommendation (2nd tab), then I should always be able to view the reassessment tab (3rd tab) in the final non-editable format that is issued to the supplier.

**Development Checklist:**
- [x] Make sure final non-editable reassessment format is only viewable by IDIR users until it is issued.
- [x] Double check the reassessment page still contains all relevant data that needs to be saved in the correct format.
- [x] Remove the hover tooltip on the Reassessment tab that states it is only viewable once a director has approved it.

**Notes:**
A wireframe for this work would probably be very helpful.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1368?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
