### ISSUE TITLE
ZEVA - Director clicking to view recommended reassessment

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1369]
**Title:** Director clicking to view recommended reassessment

**Description:** As an IDIR Director:

- When the Director clicks on a reassessment (in recommended status) they should be taken to the 3rd tab - Reassessment.

- On the Reassessment (3rtd Tab) there should are two buttons - Return to Analyst and Issue Assessment.  Remove the apostrophes from the Return to Analyst button.

- The Issue Assessment button should not appear on the Reassessment Recommendation tab, the second tab. 

**Purpose and benefit to user:**
The Director will be taken to the most relevant screen that they are being asked to review and approve, and the screen will look exactly like the one that will be issued to the supplier (the notice of reassessment).

**Acceptance Criteria:**
- [ ] Given I am a gov Director, when I am clicking to view a recommended reassessment, then I want to be taken straight to the 3rd tab - the final notice of reassessment.
- [ ] Given I am a gov Director, when I am viewing the recommended reassessment (2nd) tab, then I should not see issue assessment button

**Development Checklist:**
- [ ] Update the row click handler on the model year report list view to automatically load the 3rd tab for directors
- [ ] Remove the quotations from the Return to Analyst Button on the 3rd tab of a reassessment
- [ ] Remove the reassessment button from showing on the 2nd tab of a reassessment

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1369?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
