### ISSUE TITLE
Zeva pipeline - replace BCDK based pipeline with Helm based pipeline

### ISSUE THREAD

**Issue by kuanfandevops** [bcgov/zeva#1429]
Zeva Helm templates have been created . It is the time to replace the BCDK pipeline with Helm Charts based pipeline.

**Comment by kuanfandevops** [comment]
Applied the Helm Pipeline to both Zeva Dev and Test environment.

**Comment by kcabhar** [comment]
Kuan gave the okay to close the ticket.

**Comment by kuanfandevops** [comment]
Zeva is using Helm now!
