### ISSUE TITLE
ZEVA - Limit Credit Applications to 2,000 VIN

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1451]
**Title:** Limit Credit Applications to maximum 2,000 VIN

**Description:** Large credit applications are very hard to manage for IDIR users. Presently there is an upper limit of 50,000 VIN specified in the first tab (Instructions) of the Excel download template, this is too large. Change this value to 2,000.

Also the heading on the Credit Application page as per the wireframe.

Upload ZEV Sales Information (Maximum 2,000 VIN per application)

I'm not sure if the Excel file has a restriction of 2,000 rows or if the upload function gives an error message if they do include more than 50,000 lines. This may require some investigation as to how this is actually handled.

**Wireframe:** 
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/134764132?mode=fm

**Purpose and benefit to user:**

**Acceptance Criteria:**

- [ ] Given I am a BCeID Zeva User, When I am submitting a credit application, I will receive an error if I try to submit more than 2,000 VIN in an application.

**Development Checklist:**
- [ ] See if number of rows can be restricted on excel, restrict to 2000
- [ ] On the backend, check number of rows and return error if there are more than 2000
- [ ] Update frontend instructions to reflect changes 

**Notes:**

**Comment by tim738745** [comment]
@airinggov Currently, the way this works is if the spreadsheet contains more than 50,000 rows, only the first 50,000 will be read, and the rest will be silently ignored. So by changing the upper bound to 2000, only the first 2000 will be read, and any additional records will be ignored (there are no error messages for the user).

**Comment by airinggov** [comment]
@tim738745 I wonder if we can also limit the amount of rows in the Excel template. I think you can do this in Excel but not sure it is possible in the template that we generate.

**Comment by airinggov** [comment]
@tim738745 there is error checking when the Excel file is uploaded. Perhaps we can add a line count check and return a message; Excel file exceeds 2,000 lines

**Comment by tim738745** [comment]
@airinggov yes, you're right; I have added the error checking/message

**Comment by airinggov** [comment]
@tim738745 can you remove the text "Please download the template again and try again." from the error message?

![2000errormsg.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/95412b04-73f2-4ba3-a9c3-2be70b8758c5)

**Comment by tim738745** [comment]
@airinggov sure!
