### ISSUE TITLE
ZEVA - Add count of ZEV model sales issued to ZEV Model page

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1452]
**Title:** Add count of ZEV model sales issued to ZEV Model page, both IDIR and BCeID. 

**Description:**
As a ZEVA user I'd like to see the amount of sales that have been issued for individual ZEV models on the index page. 

**Wireframe:**
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/131174642?mode=fm

**Purpose and benefit to user:**
They get cool info. This is the type of analytics that can be delivered by CTHUB but this is also for BCeID users. So this would be required in ZEVA until we have a public version of CTHUB or a dashboard we can add to the BCeID side of ZEVA.

**Acceptance Criteria:**

- [ ] Given I am a IDIR or BCeID ZEVA user with access to the ZEV Models page, When I am looking at the ZEV Models index page, then I can see a running count of the sales issued for individual models.

**Development Checklist:**
- [ ] A. Add a new column with count of ZEV model sales issued to the  ZEV Model page for reference see the attached wireframe.
- [ ] B. Fetch the sales count from the database and display into the front end.
- [ ] C. Make sure that the visibility is for the IDIR or BCeID ZEVA user with access to the ZEV Models page.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1452?planning-poker) with Zenhub @AlexZorkin @tim738745 @vibhiquartech @jig-patel
