### ISSUE TITLE
ZEVA - Index pages, React tables are missing the paging option

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1453]
**Describe the Bug**
As an IDIR or BCeID Zeva user the main index pages with React tables are missing the paging component to set amount of records per page etc.

**BCeID**
Compliance Reporting
Credit Applications, Transfers
ZEV Models
Administration
•	Users

**IDIR**
Compliance Reporting
Credit Applications, Transfers, Agreement
ZEV Models
Vehicle Suppliers
•	Users
Administration
•	Users

**Expected Behaviour**
These index tables should have the paging component.

![paging.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/7fd27076-cbff-4b6d-92cc-596fd6eab828)

**Actual Behaviour**
No paging component.

**Implications**
Users just get a long list that they can't adjust the amount of records displayed.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: Any
1. Go to pages listed above
2. Scroll to bottom of React tables

**Acceptance Criteria**
- [ ] Given I am an IDIR user when I am viewing the vehicle supplier users, administration users, compliance reporting, credit applications, transfers, agreements, ZEV models or vehicle suppliers I should see the pages component to be able to set how many records I want to see on the page.
- [ ] Given I am a BCeID user when I am viewing the compliance reporting, credit applications, transfers, ZEV models or vehicle suppliers I should see the pages component to be able to set how many records I want to see on the page.
- [ ] Given I am a BCeID administrator when I am viewing the vehicle supplier users I should see the pages component to be able to set how many records I want to see on the page.

**Development Checklist**
- [ ] Add the paging component and have it display correctly on the pages listed.

**Additional Information**
Please also choose a table that is performing the most poorly (loads the most slowly) and implement server-side pagination for it - this will entail managing the state of the table (page number, number of pages, filters, sorts). (This is a different card - #1842)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1453?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech
