### ISSUE TITLE
ZEVA - Error message received on credit application submission (BCeID)

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1463]
**Describe the Bug**
A user (Jaguar Land Rover) reported repeatedly seeing an error message when they submitted a credit application to government, after it had been returned to the supplier by government. The credit application was successful received by government.

**Expected Behaviour**
The BCeID user should not see an error message when they submit a credit application that has been returned by government.

**Actual Behaviour**
The BCeID user sees an error message when they submit a credit application that has been returned by government. This was last seen on submission of CA-423 in production.

**Implications**
The error suggests to the user that the credit application has failed, but this is not the case.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Go to Credit applications (BceID user)
2. Create and submit a credit application to government
3. Government return credit app to supplier
4. Supplier updates credit app and re-submits to gov
5. See error message

**Notes**
-since it is actually submitting/updating the database, the error could be on the frontend and related to a redirect after submitting?

**Comment by JulianForeman** [comment]
Saw this ticket; wanting to add more context that Alex, mentioned this is most likely a session issue.  Unless this happens with any and all submissions under the same circumstance it's probably not a redirect issue.  Since the submission is still being processed by our backend successfully, the culprit is most likely the silent token renewal.

**Comment by jdon-zev** [comment]
Issue to be closed - will revisit if this is reported again.
