### ISSUE TITLE
ZEVA - Write Unit Tests for Supplementary Container Component

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1467]
**Describe the task**
There are currently no unit tests on the frontend for the Supplementary Container components so we would like to add some to reach 30% coverage.

**Purpose**
Adding unit tests will increase the confidence in capturing the business logic and increase the longevity of the application.

**Acceptance Criteria**
- [ ] Create a new tests directory in supplementary directory
- [ ] Create a test file SupplementaryContainer.test.js in the supplementary directory
- [ ] Write unit tests to reach 30% coverage in the SupplementaryContainer Component

**Additional context**
- use the jest --coverage command to view the current coverage percentages for the files

**Comment by jdon-zev** [comment]
Not something that can be user tested. Close ticket.
