### ISSUE TITLE
ZEVA - store credit application warnings

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#1469]
**Title:**
Store credit application warnings

**Description:**
Credit application warnings are derived from ICBC data, which changes from time to time. Therefore, it could be the case that the warnings also change from time to time.

We want the warnings that an analyst sees right before they recommend an application to the director to be equal to the warnings that the director always sees for that application after it is recommended.

**Wireframe:** <link>

**Purpose and benefit to user:**
Directors will have confidence that the content of credit applications they are reviewing won't change over time.

**Acceptance Criteria:**

- [ ] Given I am an analyst, if I see a set of warnings W associated with a credit application C immediately before I recommend it, then when I do recommend it, W is stored in the database.
- [ ] Given I am a director, when I am reviewing C, I always see the same warnings W.

**Development Checklist:**
(1)   Create a new db table to store warnings (some columns may include: sales_submission_content_id, warning_type, icbc_upload_date_id, etc).
(2)   When an analyst recommends a credit application, save the warnings they currently see on the page.
(3)   Display, all the time, exactly these warnings to the director when they are reviewing the application.
(4)   Of course, new models, serializers, viewsets, frontend changes, etc. will have to be made.

**Notes:**

**Comment by jdon-zev** [comment]
I don't think what Tim has here works. The point at which we want to fix the ICBC warnings is when the analyst recommends to the Director that credits should be issued for that credit application. Up to that point the analyst may be re-running checks against ICBC data or making manual changes to the results of that check. Once the analyst has finalized what is to be issued and sent it up tot he Director to issue it should never change from that point on.
Note that if the Director send the credit application back tot he analyst then it should be possible to update the result of the ICBC check again. 
I think this means we should maintain a permanent record of the results in the 'Recommended' and 'Issued' states.

**Comment by airinggov** [comment]
We not just once at the point of being Issued?

**Comment by jdon-zev** [comment]
The Director relies on the analyst to run the ICBC check and thoroughly check the credit application so that only eligible sales receive credits. If the result can change (automatically) after the analyst has recommended it, this would be confusing and undermine the Directors confidence in the work of the analyst.

**Comment by tim738745** [comment]
I updated the card to reflect the discussion in the comments above.

**Comment by airinggov** [comment]
We might update how the error Excel download is created to use this new database

**Comment by tim738745** [comment]
PR build: https://zeva-dev-1978.apps.silver.devops.gov.bc.ca/
