### ISSUE TITLE
ZEVA - Write Additional Unit Tests for the SupplementaryAnalystDetails Component

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1499]
**Describe the task**
Write Unit Tests for the SupplementaryAnalystDetails Component in ZEVA

**Purpose**
We want to write unit tests in ZEVA to ensure that the codebase is robust and error-free. By doing so, we can catch and fix any issues early on in the development cycle, before they become more difficult and time-consuming to fix.

**Acceptance Criteria**
// TESTS TO WRITE

// as an analyst
// if i view a supplemental report in submitted status
// i should be able to edit fields, add comments to supplier or director,
// click a radio button for the assessment, and save/recommend to director or return to supplier

// as an analyst
// if i view a supplemental report in recommended status
// I should be able to view a read only version of all 3 tabs

// as an analyst
// if i view a supplemental report in any status
// I should be able to view all 3 tabs

// as an analyst
// if i view a reassessment report in any status
// I should be able to view the second two tabs

// as an analyst
// if i view a supplemental report in submitted status
// I should be able to view a editable version of all 3 tabs

- [ ] Write any additional comprehensive unit tests for the SupplementaryContainer component, ensuring that each test case covers a specific functionality or edge case.
- [ ] Ensure that the code coverage for the SupplementaryContainer component is at least 50%.

**Additional context**
use the command 'npm run test' in the frontend directory to get a coverage report for ZEVA

**Comment by jdon-zev** [comment]
Can't be user tested. Close card.
