### ISSUE TITLE
ZEVA - Write Unit Tests for SupplementaryCreate Component

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1500]
**Describe the task**
Write Unit Tests for the SupplementaryCreate Component in ZEVA

**Purpose**
We want to write unit tests in ZEVA to ensure that the codebase is robust and error-free. By doing so, we can catch and fix any issues early on in the development cycle, before they become more difficult and time-consuming to fix.

**Acceptance Criteria**
- [ ] Write a Unit Test that ensures that the component renders correctly
- [ ] Write a Unit Test that ensures that comments are rendered correctly
- [ ] Write a Unit Test that tests whether the compliance report checkboxConfirmed renders only with the correct permissions
- [ ] Write a Unit Test that covers button render logic based on feature flags
- [ ] Write any additional comprehensive unit tests for the SupplementaryContainer component, ensuring that each test case covers a specific functionality or edge case.
- [ ] Ensure that the code coverage for the SupplementaryContainer component is at least 35%.

**Additional context**
use the command 'npm run test' in the frontend directory to get a coverage report for ZEVA

**Comment by jdon-zev** [comment]
Can't be user tested. Close card.
