### ISSUE TITLE
ZEVA - Write Unit Tests for SupplementarySupplierDetails Component

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1502]
**Describe the task**
Write Unit Tests for the SupplementarySupplierDetails Component in ZEVA

**Purpose**
We want to write unit tests in ZEVA to ensure that the codebase is robust and error-free. By doing so, we can catch and fix any issues early on in the development cycle, before they become more difficult and time-consuming to fix.

**Acceptance Criteria**
- [ ] Create a new SupplementarySupplierDetails.test.js file
- [ ] Write a Unit Test that ensures that the component renders correctly
- [ ] Write a Unit Test that checks that the correct tabs are rendered
- [ ] Write a Unit Test that checks render logic on the currentStatus variable
- [ ] Write a Unit Test that checks for the correct permissions for the confirmationCheckbox
- [ ] Write any additional comprehensive unit tests for the SupplementaryContainer component, ensuring that each test case covers a specific functionality or edge case.
- [ ] Ensure that the code coverage for the SupplementaryContainer component is at least 50%.

**Additional context**
use the command 'npm run test' in the frontend directory to get a coverage report for ZEVA

**Comment by kcabhar** [comment]
Not one that can be user tested - Alex approved and merged
