### ISSUE TITLE
ZEVA - Add More Descriptive Email Body Text for Better Test Environment Clarity

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1523]
**Describe the task**
The goal of this sprint ticket is to update the email notification methods to include additional descriptive text in the email body. 

**Purpose**
This will improve the testing experience in the test environment by providing better context and understanding of which actions in the application are triggering specific emails.

**Acceptance Criteria**
(1) Given I am a test ZEVA user, when I get a system generated email, the email contains additional descriptive text specifying details such as the action that triggered the email, user or system events, and a timestamp.

(2) Given I am a production ZEVA user, when I get a system generated email, it should look the same as before - there should be no additional descriptive text.

**Development Checklist**
- [x] Identify the current email notifications being used in the application.
- [x] Figure out how to robustly condition code based on environment.
- [x] Modify the email notification methods to include additional descriptive text in the email body.
- [x] Ensure that the additional descriptive text is only added in the test environment, not affecting production emails.
- [x] The descriptive text should include relevant information about the action that triggered the email, such as the name of the action, user or system events, and a timestamp.
- [ ] Test the modified email method to confirm that the additional descriptive text is included in the email body and aids in understanding the context of the email.
- [x] Update documentation and notify the testing team of the changes to the email method.

**Additional context**
- Please remember to keep the changes isolated to the test environment to avoid any unintended consequences in the production environment.
- Coordinate with the testing team to gather feedback on the effectiveness of the additional descriptive text and make any necessary adjustments before marking the ticket as complete.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1523?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by jdon-zev** [comment]
No emails being received at all in testing.

**Comment by JulianForeman** [comment]
This seems like an entirely new issue that is being caused by a portion of the code I did not modify.  I think we should create an estimate a new ticket on this for next sprint.

**Comment by jdon-zev** [comment]
Not possible to test as ZEVA is no longer sending any emails. New card to fix that to be created.
