### ISSUE TITLE
ZEVA - Pre-process ICBC data for February

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1549]
**Describe the task**
Process the ICBC data for February so that it can be uploaded into ZEVA.

**Purpose**
The field from ICBC is too large to be uploaded into ZEVA without pre-processing.

**Acceptance Criteria**
- File is processed so that it is small enough for the ZEVA system to accept.

**Additional context**
- File is stored in Teams under the files tab in the ZEVA channel.
- See Alex for questions.

**Comment by AlexZorkin** [comment]
The processed file for 2023-02-28 has been upload to the ZEVA_ICBC folder in teams.
