### ISSUE TITLE
ZEVA - Credit application issue Sept 30 checkbox

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1574]
**Title:** Credit application issue Sept 30 checkbox checked by default

**Description:** Credit applications have a checkbox to backdate the issue date to sept 30 if they are to be processed as part of a model year report. The checkbox is not checked by default forcing the analyst to make the decision to check the box.

Make the checkbox checked by default if there is a Model Year Report in submitted status, otherwise it can remain unchecked.

**Wireframe:** 
![issue-sept-30.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/111f166c-63ba-4dfe-8eb8-fff2eb151e3c)

**Purpose and benefit to user:**
analyst is less likely to forget to check the issue as sept 30 checkbox.

**Acceptance Criteria:**

- [ ] Given I am a IDIR analyst, When I am processing a credit application to recommend to the director during the time period when Model Year Reports are also being processed, then the issue as sept 30 checkbox is checked by default if there is a Model Year Report in Submitted status.

**Development Checklist:**
- [ ] If any model year report for the organization is in a submitted status, set checkbox boolean to default true.

**Notes:**

**Comment by JulianForeman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1574?planning-poker) with Zenhub @emi-hi @AlexZorkin @tim738745
