### ISSUE TITLE
ZEVA - Remove AccountBalance table

### ISSUE THREAD

**Issue by emi-hi** [bcgov/zeva#1589]
**Describe the task**
Remove all uses of AccountBalance table

**Purpose**
Maintaining two tables (transactions and balance) was causing issues with data as the account balance table was supposed to keep a running total but we keep having discrepancies between the two. Instead we are now grabbing the organization by using the aggregate credit transactions function and calculating the total in a method on the organization model. We should remove any code that reads or modifies the account balance table. 

**Development Checklist**

- [ ] remove references to accountBalance table.
   - If a record is being created in account balance that code can be deleted because we will not be maintaining that table. 
  - If it is being grabbed in a filter or get to display or use the balance anywhere switch that to use the CreditTransaction table, the balance is a calculated field
- [ ] delete accountBalance table and create migration for that
- [ ] make a copy of that table, export all rows and store on teams so there is a backup

**Comment by jdon-zev** [comment]
Not possible to user test - card to be closed.
