### ISSUE TITLE
ZEVA - Reassessments in the negative - add to deficit table

### ISSUE THREAD

**Issue by emi-hi** [bcgov/zeva#1590]
**Description:**
If a supplier goes into the negative during a reassessment, we need to add a record to the deficit table to track that they are in deficit, similar to model year reports. In addition, we need to make sure that the whole workflow is working correctly with deficits in general

**Acceptance Criteria:**

- [ ] Given I am a director, when i issue a reassessment with a negative closing balance, it is recorded in the organization_deficit table
- [ ] if a reassessment is created, delete whatever is in the deficit table for that model year report and create a new one to replace it?

**Development Checklist:**
- [ ] follow the same way as the model year report for adding a deficit from a reassessment to the organization_deficit table

**Notes:**

**Comment by jdon-zev** [comment]
Not user tested. To be fully tested once the testing scenarios are ready for complete testing of supp reports and reassessments.
