### ISSUE TITLE
ZEVA - Credit Transaction Page Loading Performance Issues for Director

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1613]
**Description:**
The Director role is experiencing performance issues with the credit transaction page taking a long time to load.

**Expected Behaviour:**
Credit transaction page should load instantly or at least within a second.

**Actual Behaviour:**
Credit transaction page takes 10+ seconds to load.

**Implications:**
The user is frustrated because it takes longer than necessary to access credit transaction information.

**Steps To Reproduce:**

Log in as a Director.
Navigate to the credit transaction page.
Observe the loading time for the credit transaction page.

** Development Requirements **
- [ ] Assess why the view takes so long to load
- [ ] If query time is the main issue then Implement pagination to limit the result size
- [ ] Report the speed increase before and after and add a comment into this ticket reporting the difference.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1613?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by jdon-zev** [comment]
Tim, as discussed:
- We would like to be able to sort on the basis of date
- We would like to change the filtering so that the user has to click return/enter instead of typing ";" at the end of search terms.

**Comment by tim738745** [comment]
@jdon-zev I took a look at the "Date" field we're using for this table, and its derivation is quite complex - so much so that sorting by it properly could be very difficult. I think we saw something similar in TFRS, where one of the date fields in the compliance reports table was also very complex, and what we did was we added a "Last Updated On" field and allowed users to sort by that. Could we do the same thing here? Please let me know! Thanks.

**Comment by airinggov** [comment]
Would it be effective (load immediately) to have a new table (not a react table) that just displayed the records with no filtering or sorting at all? So the link from the dashboard would query the proper status (recommend issuance)?

Then there could be a button to 'Show All' that would load the usual react table page? Sorting and filtering could be removed from 4 columns (Sales/Credits columns)

**Comment by tim738745** [comment]
@jdon-zev sounds good! I did already implement the requested changes (sort by date, filter by hitting 'enter'); perhaps I could commit that and we can make a new card for the better options?
