### ISSUE TITLE
ZEVA - Redirect Issue After Approving Credit Transactions for Director

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1614]
**Description:**
When the Director approves a credit transaction, or anyone refreshes the page or types a url directly in, or BCEID submits a sales submission they are redirected back to the login screen instead of staying on the page of the credit application they have approved.

**Expected Behaviour:**
The user should stay on the page they are on when they perform an action or go to the page they want when they type a url in.

**Actual Behaviour:**
The Director approves a credit application and is redirected to the login page.

BCEID creates a sales submission and submits to government and is redirected

anyone refreshes and is redirected

**Implications:**
The user is not sure if the credit application has been issued and they have to log in again and navigate back to the credit application to check if it was issued successfully.

**Steps To Reproduce:**

Log in as a Director.
Navigate to a credit application.
Approve the credit application.
Observe the page redirection after approval.

etc etc

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1614?planning-poker) with Zenhub @JulianForeman

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1614?planning-poker) with Zenhub @emi-hi
