### ISSUE TITLE
ZEVA - Email notifications not working on Prod or Test

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1633]
**Describe the Bug**
For approximately the last 10 days no-one in government has received any email notifications from the ZEVA system in either test or prod.

**Expected Behaviour**
Users expect to receive emails when they are signed up for them in the ZEVA system.

**Actual Behaviour**
User are not receiving any emails they are signed up for.

**Implications**
The notifications feature is not working to alert users to actions they need to take in the ZEVA system.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Perform an action that's supposed to generate notification emails (e.g. initiate a credit transfer).
2. Wait for emails to be sent out to the people associated with the action.

Notes:
In the test environment the openshift logs showed: 
"Unable to send email! The QuerySet value for an exact lookup must be limited to one result using slicing."
I think this error is caused by line 319 in send_email.py (notifications is a list, but filter() is expecting just a single id)

This line of code is not in prod (1.46.0) yet, so we still have to confirm if it's happening there, and if so, investigate why.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1633?planning-poker) with Zenhub @AlexZorkin @emi-hi @JulianForeman @tim738745

**Comment by jdon-zev** [comment]
Not resolved. Still no emails working in the test or prod systems. Card to be closed and a new one to be opened for Alex to look at.
