### ISSUE TITLE
ZEVA - Clear Penalties from Database when Reassessment Decision Changes

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1635]
**Describe the task**
if an analyst  inputs a penalty (lets say 20000) and saves a draft, then goes back and decides they are in compliance and saves the draft again or recommends with a new radio selection, the 20000 stays in the database and on the frontend instead of being set to 0 once saved, but it should be set to 0 because there is no longer a penalty. 

**Purpose** 
To maintain data integrity and accuracy by removing penalties that are no longer applicable, preventing potential errors in the application's calculations or reports.

**Acceptance Criteria** 

- [x] Identify the event where the reassessment decision changes
- [x] Clear the penalty from the database when a reassessment is saved with a decision without a penalty
- [x] Verify that the penalty is removed from the database and not displayed in the application

**Additional context** 

Ensure existing functionality related to penalties is not affected

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1635?planning-poker) with Zenhub @AlexZorkin @emi-hi @JulianForeman @tim738745

**Comment by jdon-zev** [comment]
From user testing - there are still problems when the user tries to clear out a penalty amount. Selecting a radio button that does not have an associated penalty (the first two buttons) does not clear a penalty amount that has been entered. The user must select the 3rd radio button and then manually delete the penalty amount, but when they do this and then either save or recommend the assessment the system crashes (we're sorry error is seen).
