### ISSUE TITLE
ZEVA - Fix Draft Model Year Report to Properly Pull Reassessed LDV Sales Data

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1636]
**Describe the task**
Fix the issue where supplier info inside the draft model year report doesn't pull reassessed LDV sales from the prior year.
The prior year ldv sales is used to calculate the volume of the supplier so we do need the correct value.
**Purpose**
To ensure that the draft model year report displays accurate information, which helps suppliers to make informed decisions and comply with regulations.

**Acceptance Criteria**

- [x] Identify the root cause of the issue
  - the root cause of the issue is that we haven't finished the reassessments feature so we are not doing anything with the numbers (ldv sales, reductions, etc) yet
  - we need to write a service that updates those values when reassessment is issued
- [x] Implement a fix to properly pull reassessed LDV sales data from the prior year
- [x] Verify that the draft model year report displays the correct data

**Additional context**

Ensure that the fix does not affect other parts of the application or data retrieval

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1636?planning-poker) with Zenhub @JulianForeman @tim738745 @emi-hi @AlexZorkin
