### ISSUE TITLE
ZEVA - Prevent App Crash when Analyst Returns a Report and Navigates to Compliance Dashboard

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1637]
**Describe the task**
Resolve the issue causing the application to crash when an analyst returns a report to the supplier and attempts to return to the compliance dashboard.

**Purpose**
To ensure the application's stability and maintain a smooth user experience for both analysts and suppliers.

**Acceptance Criteria**

- [x] Identify the root cause of the crash (routing or session issue)
- [ ] Implement a fix to prevent the application from crashing when returning to the compliance dashboard
- [ ] Verify that the fix works and the application no longer crashes in this scenario

**Additional context**

Test the fix thoroughly to ensure it doesn't introduce new issues or negatively impact the user experience

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1637?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745 @vibhiquartech

**Comment by JulianForeman** [comment]
I can't replicate this bug on test; most likely it was/is a session issue but even waiting on the assessment page for ~5 minutes before actually returning the report does not throw an error.
