### ISSUE TITLE
ZEVA - Maintain Correct Name of User Who Submitted Status Update in History Component

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1640]
**Describe the task**
Ensure the history component maintains the name of the user who submitted the status update, even when the comment or status is changed.

**Purpose**
To provide accurate and consistent information on the history component, making it easier to track and audit changes made by different users.

**Acceptance Criteria**

- [ ] Investigate the current implementation of the create_user function and how records are being handled
- [ ] Identify the root cause of the issue with the name being changed
- [ ] Change compliance history for when a reassessment is saved for the first time to say Created instead of saved.
- [ ] Implement a fix to maintain the correct name of the user who submitted the status update, regardless of comment or - status changes
- [ ] Verify that the fix works and the history component displays the correct name

**Additional context**

Ensure that the fix does not negatively impact other parts of the application or data storage
Test the fix thoroughly to ensure it doesn't introduce new issues or negatively impact the user experience

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1640?planning-poker) with Zenhub @AlexZorkin @emi-hi @JulianForeman @tim738745
