### ISSUE TITLE
ZEVA - credit application error count

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1647]
**Describe the Bug**
The error count within the error type filter drop down are not accurate

**Expected Behaviour**
As an IDIR analyst processing a credit application on the VIN detail page, the drop down list to filter by error type includes a count of each error type found in the application. This should be a count of each error contained in the entire application, not just the current page.

**Actual Behaviour**
The count is not accurate to the actual amount of specific errors found.

**Implications**
The count is not helpful if it isn't correct.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR\analyst
1. Go to credit application
2. Click on Verify with ICBC Data
3. Click drop down to Filter by Error Type
4. Seer error of counts contained within brackets next to each error type

![ca-error-count.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/acf34e2b-68ed-41c2-8d11-208c5f403b1f)

**Acceptance Criteria**
- [ ] Given I am an IDIR user or an Analyst viewing the error list dropdown; I should see the correct number displayed on each error for the whole application.

**Developer Checklist**
- [ ] Check where the error numbers are coming from (Do we store them in the backend or are they calculated on the front)
- [ ] Update the logic to correctly display the error count in the CreditRequestVinListPage.

**Notes**
This is probably an error pulling data, because the frontend is set up to default to 0 if there is nothing in the corresponding error variable.

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1647?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745

**Comment by airinggov** [comment]
still getting some incorrect counts, Toyota example in test display a count of 9 (41) errors but there are only 8

**Comment by tim738745** [comment]
@airinggov I'll take a look

**Comment by tim738745** [comment]
@airinggov I took a look and the reason why you're only seeing 8 (41) errors is because, on the frontend, we do not repeat errors for the same VIN if they have the same error code. For VIN 5TDEBRCH7LS012489 on that page (the second line), there's actually 2 (41) errors (MY mismatch and Make mismatch), so the total of nine is correct. Perhaps in the "warning" column it should say "41, 41"?

**Comment by airinggov** [comment]
@tim738745 oh interesting, so that is only with 41 errors, the rest should be fine. I think we can just leave it for now with that explanation, see what the business says

**Comment by tim738745** [comment]
@airinggov yes, it should only be with (41) error codes, because, from what I can tell, ['INVALID_MODEL', 'MODEL_YEAR_MISMATCHED', 'MAKE_MISMATCHED'] errors all associated with the (41) error code, but every other error code is associated with only one error.
