### ISSUE TITLE
ZEVA - Credit Application History text

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1648]
**Title:** Credit Application History text, add Submission Date

**Description:** The credit application History information in the Status banner is visible to both BCeID and IDIR users. When the BCeID user first uploads and save a credit application the following message is displayed

History - Excel template BC-ZEVA_Sales_Template_Toyota__2022-10-04.xls uploaded and auto-saved, Oct 4, 2022 by Vehsup Signer.

Once the BCeID user submits the application to government we'd like the text updated to

History - Excel template BC-ZEVA_Sales_Template_Toyota__2022-10-04.xls uploaded and auto-saved, Oct 4, 2022 by Vehsup Signer, submitted to Government of B.C. Oct 4, 2022, by Vehsup Signer.

**Wireframe:** <link>

**Purpose and benefit to user:** The submission date is more important to IDIR users and is also of historical interest to the supplier. This date is lost to the supplier after government processes the application.

**Acceptance Criteria:**

- [ ] Given I am a idir\analyst or bceid\zeva user, When I am viewing a credit application, then I can see the submission date as part of the history information.

**Development Checklist:**
- [ ] A - Update a text as per above requirement to include submission date when user submits the application 

**Notes:**

**Comment by AlexZorkin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1648?planning-poker) with Zenhub @emi-hi @jig-patel @JulianForeman @tim738745

**Comment by JulianForeman** [comment]
This already seems to be the existing logic.

**Comment by airinggov** [comment]
yes it does, I'll close this
