### ISSUE TITLE
ZEVA - Prevent credit application errors during compliance period by adding new logic

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1652]
**Description:**
As an IDIR analyst processing a credit application (CA) for a vehicle supplier, implement the following logic to prevent errors during the compliance period:

Check if the vehicle supplier's MY Report status is SUBMITTED, RECOMMENDED, or RETURNED (exclude DRAFT status).

Set MYR variable to the year of the MY Report.

If the current date is after September 30th of MYR + 1 year, follow the steps below:

a. If the CA submission date is after October 20th of MYR + 1 year, prevent any action on the CA or block recommending it to the Director (to allow analyst work to start).

b. If the CA submission date is before October 20th of MYR + 1 year, issue VIN credits for MY = MYR as of September 30th of MYR + 1 year. Flag all other MY VIN credits with a new error code (71*) and return them without issuing credits.

If the current date is before September 30th of MYR + 1 year, issue all MY VIN credits as of the processing date.

*New error code 71 – Model year cannot be issued with an active compliance report.

Additionally, consider preventing suppliers from creating or submitting CAs when they have an active MY Report submitted to the government.

**Purpose and benefit to user:**
The purpose of this update is to reduce errors in the credit application process during the compliance period. This will streamline the process for IDIR analysts, ensure accurate credit allocation, and provide a better user experience for vehicle suppliers and government users.

**Acceptance Criteria:**
- [ ] Given I am an IDIR analyst, when I am processing a CA with a submitted, recommended, or returned MY Report, then the new logic should be applied to prevent errors during the compliance period.
- [ ] Given I am a vehicle supplier, when I am submitting a CA with an active compliance report, then I should receive an error message (code 71) if my submission does not meet the new logic requirements.

**Development Checklist:**
- [ ] Implement the new logic in the credit application processing system to handle MY Reports with submitted, recommended, or returned status during the compliance period.
- [ ] Create a new error code (71) for situations where the model year cannot be issued with an active compliance report.
- [ ] Update the user interface to display the new error code (71) and an explanatory message to vehicle suppliers when their submission does not meet the new logic requirements.

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1652?planning-poker) with Zenhub @AlexZorkin

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1652?planning-poker) with Zenhub @JulianForeman @tim738745 @jig-patel

**Comment by AlexZorkin** [comment]
There is a period of time between when a model year report has been submitted and when it actually gets assessed. In this period the supplier can upload additional sales submissions which could potentially alter the credits issued at the time of assessment. We need to add some additional business logic to automatically back date sales to Sept. 30th of the model year for vehicles in that model year. If vehicles are uploaded that have a model year later than the current open assessment period, then they need to be assigned a new warning “71” which is “Model year cannot be issued with an active compliance report”.

Development Requirements:

- add new warning 71 to frontend app/constants/errorCodes.js to match new backend warning property 71
- sales_submission_content model @property def warnings(self): will need logic to account for warning 71
- Review SalesSubmission update method to ensure the RecordOfSale logic still works with warning 71
- On Sales Submission create/update, write business logic similar to the following sudo code to ensure only the vehicles from the correct model year are added as pending credits:

IF OPEN MYR STATUS == [‘SUBMITTED, RECOMMENDED, or RETURNED]
	IF CURRENT REAL DATE > compliace_year_sept_30 + 1 year
		IF CURRENT REAL DATE > compliace_year_oct_30 + 1 year
			NO ACTION ALLOWED, beyond applicable dates
		ELSE IF CURRENT REAL DATE < compliace_year_oct_30 + 1 year
			action allowing credits for vehicles within that model year, but set their effective date to Sept30, all other vin entries get a 71 warning flag (may need to set snapshot)
	ELSE IF CURRENT REAL DATE < compliace_year_sept_30 + 1 year
		ISSUE all credits as of the processing date

**Comment by kcabhar** [comment]
Additional notes from Alex:

The problem:
When a model year report is submitted for model year 20xx
It includes the credits from all ZEV sales that have been submitted to government of model year 20xx but have not yet been issued (shown as pending credits)
These pending credits need to be backdated when they are issued so that the supplier has these credits in their account on the compliance date of Sept 30th (of the calendar year prior to model year 20xx)

Credits should be backdated when:
They are part of a credit application in submitted status
And a model year report has subsequently been submitted to government
And the credits are of the same model year as the submitted model year report
Otherwise, they should be tagged as 71 error and not issued.
