### ISSUE TITLE
ZEVA - SQL Insert Statement for Consistent User Scenario Testing

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1654]
**Describe the task**
Create an SQL insert statement to initialize the test database for our ZEVA application.

**Purpose**
This task is essential for ensuring a consistent and reliable testing environment. By initializing the test database with a predefined set of data, we can reset the database to a known state, allowing testers to execute user scenarios effectively and thoroughly test the application.

**Acceptance Criteria**

- [ ] Develop a comprehensive SQL insert statement that covers all required tables and data fields for ZEVA's test database.
- [ ] Ensure the insert statement initializes the database with representative sample data for all user scenarios.
- [ ] Create a script to automate the process of resetting the database to its initial state using the SQL insert statement.
- [ ] Verify the accuracy and completeness of the initialized data by running tests on various user scenarios.

The following are scenarios for automated testing of re-assessment reports:
Supplier A (Large)
MY2020 Report
• All credit transaction type (all before Sept 30 2021)
• MY2020 credits (A+B)
• MY2019 credits (A+B)
• ZEV models validated
• ZEV sales
• LDV sales - 2020
• LDV sales - 3 prior years (volume class)
• Positive Final Balance

Supplier B (Medium)
MY2020 Report
• All credit transaction type (all before Sept 30 2021)
• MY2020 credits (A+B)
• MY2019 credits (A+B)
• ZEV models validated
• ZEV sales
• LDV sales - 2020
• LDV sales - 3 prior years (volume class)
• Positive Final Balance

Supplier C (Large)
MY2020 Report
MY2021 Report
• All credit transaction type
• MY2021 credits (A+B) - all btw Oct/1/21 and Sept/30/22
• MY2020 credits (A+B) - all btw Oct/1/20 and Sept/30/21
• MY2019 credits (A+B) - all btw Oct/1/19 and Sept/30/20
• ZEV models validated
• ZEV sales
• LDV sales - 2021
• LDV sales - 4 prior years (volume class)
• Positive Final Balance

Supplier D (Large)
MY2020 Report
MY2021 Report
• All credit transaction type
• MY2021 credits (A+B) - all btw Oct/1/21 and Sept/30/22
• MY2020 credits (A+B) - all btw Oct/1/20 and Sept/30/21
• MY2019 credits (A+B) - all btw Oct/1/19 and Sept/30/20
• ZEV models validated
• ZEV sales
• LDV sales - 2021
• LDV sales - 4 prior years (volume class)
• Negative Final Balance
**Additional context**

- The test database schema and structure should be aligned with the current production version of ZEVA.
- The SQL insert statement should be compatible with our preferred database management system PostgreSQL
- Coordinate with the testing team to gather a comprehensive list of user scenarios that need to be covered during testing.
- Keep in mind that the test data should not contain any sensitive or personally identifiable information (PII).

Development checklist:
A - Review the schema of database and identify all the tables that need to be populated with sample data.
B - For each table, determine the data fields that are required to be populated with sample data. 
C - Based on the identified tables and required data fields, write an SQL insert statement for each table that inserts the representative sample data. 
D -  Create a script that automates the process of resetting the database to its initial state using the script.

**Comment by jdon-zev** [comment]
[https://app.zenhub.com/files/223241604/60deb763-d9d6-4b28-8da5-bbbea4da97f1/download](https://app.zenhub.com/files/223241604/60deb763-d9d6-4b28-8da5-bbbea4da97f1/download)

**Comment by JulianForeman** [comment]
Fake BMW Vins in case someone wants to continue this while I am away.

[https://app.zenhub.com/files/223241604/226e4dad-2295-4a9a-959a-aa105d6c7411/download](https://app.zenhub.com/files/223241604/226e4dad-2295-4a9a-959a-aa105d6c7411/download)

**Comment by kcabhar** [comment]
Julian estimates 3 going into Klefki
