### ISSUE TITLE
ZEVA - Easy Deployment of Test Data Initialization SQL Statement using Makefile for Test and Local Databases

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1657]
**Describe the task**
Develop a Makefile to easily deploy the test data initialization SQL statement to both the test database and developers' local databases in the ZEVA application, built on Django and PostgreSQL, running in an OpenShift cluster.

**Purpose**
The purpose of this task is to provide an efficient and streamlined process for deploying the test data initialization SQL statement to various environments using Makefile. This will enable developers and testers to maintain a consistent and up-to-date testing environment in their respective setups, allowing for more effective testing and development of the ZEVA application.

**Acceptance Criteria**

- [ ] Create a Makefile to automate the deployment process of the SQL statement to test and local databases.
- [ ] Ensure the Makefile is compatible with the Django, PostgreSQL, and OpenShift environment.
- [ ] Implement the Makefile, allowing developers and testers to deploy the test data initialization SQL statement with minimal manual intervention.
- [ ] Create clear documentation on how to use the Makefile, including any prerequisites, dependencies, or setup requirements.
- [ ] Test the Makefile in both the test database and local databases to ensure it functions as expected and successfully initializes the respective environments.

**Additional context**

- Coordinate with the development and testing teams to gather input on preferred deployment methods and any specific requirements or considerations.
- Keep in mind the importance of maintaining a secure environment while deploying the test data initialization SQL statement, especially when handling user data.

**Comment by jdon-zev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1657?planning-poker) with Zenhub @AlexZorkin @emi-hi @jig-patel @JulianForeman @tim738745
