### ISSUE TITLE
ZEVA - Returned Reassessment Save Error

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1661]
**Describe the Bug**
When a recommended reassessment is returned to the analyst by the director. The Assessment Message to the Supplier comment field is editable but if the analyst makes updates to it and clicks Save the updated text isn't saved. The analyst is also redirected to the index page.

**Expected Behaviour**
If the analyst changes the text in the Assessment Message to the Supplier comment field and clicks Save the changes should be saved. And the analyst should remain on the report page instead of being redirected to the index page.

**Actual Behaviour**
The updated text isn't saved and the analyst is redirected to the index page instead of just remaining on the report page.

**Implications**
The message to the supplier will be wrong.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir\analyst
1. Go to a reassessment in Returned status
2. Type text in the Assessment Message to the Supplier comment field
3. Click Save
4. Reopen report and see that changes weren't saved

Development Checklist:
1. Make sure updated text by analyst saved 
2. After successfully saved the text, it should redirect to report page

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1661?planning-poker) with Zenhub @jig-patel @JulianForeman @tim738745

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1661?planning-poker) with Zenhub @AlexZorkin

**Comment by jdon-zev** [comment]
Check - is this still a bug on test?
