### ISSUE TITLE
ZEVA - Reassessment History component error

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1662]
![returned-history-bug.PNG](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/385acc15-a3d0-4242-9e8f-534aa9a06a3f)

**Describe the Bug**
The history for when the analyst recommended the reassessment user name is being changed to the director name if they return the reassessment to the analyst.

**Expected Behaviour**
The recommended analyst user name should not be affected by the director performing an action.

**Actual Behaviour**
The history for when the analyst recommended the reassessment user name is being changed to the director if they return the reassessment to the analyst. (Should also check if it is changed if the director clicks Save)

**Implications**
History information will no be reflected accurately.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir\director
1. Go to a Reassessment in Recommended status
2. Click on Return to Analyst button (also try the Save button)
3. See the History component change the recommended line to now be the director name

**Comment by jdon-zev** [comment]
Duplicate card for this issue.
