### ISSUE TITLE
ZEVA - Allow IDIR users to download pdf of individual ZEV model details

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1668]
**Describe the task**
The Clean Transportation Branch has been in discussion with colleagues at Ministry of Transportation (MOTI). Currently automakers have to submit their ZEV details twice, once in ZEVA to have the model validated to earn credits and once to (MOTI) to get the model approved to use HOV lanes.

To streamline this process we would like to have one process for receiving details. It is proposed that the information submitted into ZEVA be shared with the MOTI team view pdf. This would only be for new models not all the historical ones in the ZEVA system. Only models that have been validated should be downloadable.

Example page - pdf create/download button would be on bottom right of page
https://zeroemissionvehicles.gov.bc.ca/vehicles/620

**Purpose**
To reduce the administrative burden for automakers providing ZEV model information to the BC government.

**Acceptance Criteria**
- [ ] IDIR analyst users can download all the information on a validated ZEV model in a form that can be emailed to MOTI's mailbox as a pdf.

**Development Checklist**
(1) Use the window.print() functionality that the "Print Page" buttons have as a way to download a vehicle details page as a pdf. So add a "Print/Download Page" button in VehicleDetailsPage.js that calls window.print() when clicked.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1668?planning-poker) with Zenhub @AlexZorkin @jig-patel @JulianForeman @tim738745
