### ISSUE TITLE
ZEVA - Reassessment Penalty Input Crash

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/zeva#1683]
**Describe the Bug**
When an analyst tries to save or recommend a reassessment with the penalty radio button selected but no value in the input area the app will crash.

**Expected Behaviour**
If an analyst attempts to save or recommend a reassessment that has a penalty but has not inputted a penalty amount they shouldn't be able to and there should be some sort of visual cue around the input box indicating it still needs a value.

**Actual Behaviour**
The app crashes when no value is inside the penalty input box and the penalty option is selected.

**Implications**
User will have to login again, repeat the process and will have to figure out why the crash happened on their own.

**Acceptance Criteria**
- [ ] Ensure app does not crash when saving or recommending a reassessment with no penalty value.
- [ ] Create a visual cue to inform the user they still need to enter a value.

**Development Checklist**
- [ ] Make sure no errors are being thrown behind the scenes even if the app isn't crashing.
- [ ] Double check there is no entry being created in the database, despite the crash when a user saves/recommends a reassessment with no penalty.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir\analyst
1. Go to a reassessment in submitted status
2. Go to the assessment tab
3. Select the has not complied with penalty radio button
4. Do not put a value inside the input box
5. Click save/recommend

**Comment by JulianForeman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1683?planning-poker) with Zenhub @AlexZorkin @tim738745 @jig-patel

**Comment by jdon-zev** [comment]
Check - is this still a bug on test?
