### ISSUE TITLE
ZEVA - No emails being sent in test or prod environments

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1709]
Describe the Bug
For approximately the last the last month no-one in government has received any email notifications from the ZEVA system in either test or prod. Julian looked into the issue but the problem is still persisting, at least in the current test environment. At the time emails stopped being sent we had been working to tidy up some of the email which were being sent in error. the two issues don't appear to be related but the timing is coincidental.

Agreed with Alex that he will now investigate the issue.

Expected Behaviour
Users expect to receive emails when they are signed up for them in the ZEVA system.

Actual Behaviour
User are not receiving any emails they are signed up for.

Implications
The notifications feature is not working to alert users to actions they need to take in the ZEVA system.

Steps To Reproduce
Steps to reproduce the behaviour:
User/Role:

Perform an action that's supposed to generate notification emails (e.g. initiate a credit transfer).
Wait for emails to be sent out to the people associated with the action.

**Comment by jdon-zev** [comment]
Al and Alex discussed this is still not working. Putting the card back to in progress.

**Comment by airinggov** [comment]
I'm getting emails, both bceid and idir. Do we need to test each individua transaction by role?

**Comment by airinggov** [comment]
Things are looking really good. Couple last things to work out. This one in particular, if fixed would allow for a production release.

As an IDIR analyst processing a credit transfer to recommend to the director. If I add and Save a comment to the Director, both suppliers receive an email when they should not.
User: JADONALD
Action: Credit Transfer to Review
Description: when transfer partner approves credit transfer
Action: Credit Transfer Accepted by Transfer Partner
Description: when transfer partner accept a credit transfer

**Comment by tim738745** [comment]
[https://app.zenhub.com/files/223241604/14938c75-ba15-48b6-b4af-4bc7f9522b8f/download](https://app.zenhub.com/files/223241604/14938c75-ba15-48b6-b4af-4bc7f9522b8f/download)

**Comment by kcabhar** [comment]
Tim estimates 3 going into Klefki

**Comment by jdon-zev** [comment]
Emails do not work in the dev environment - This needs to be tested in Test.

**Comment by jdon-zev** [comment]
Working now in test environment.
