### ISSUE TITLE
ZEVA - Delete Toyota's administrative credit reduction transaction - related to Incomplete Reassessment Feature

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1711]
**Describe the task**
We are trying to correct the incorrect credit balance for the Toyota in production which occurred due to the incomplete reassessment report feature.

To do this requires removing/deleting the administrative credit reduction transaction (Transaction ID AR-1) and checking that the balances on the transaction pages reflect this deletion.

An analyst will then carry out a reassessment of Toyota's 2020 model year report. This will alter Toyota's 2020 model year report credit reduction transaction.

This is the Toyota transaction page, and attached is a screenshot with AR-1 highlighted in red.
https://zeroemissionvehicles.gov.bc.ca/organizations/18/credit-transactions

**Purpose**
Toyota communicated a change to their total LDV saes for MY2020. At that time the reassessment feature was not available so in order to try and account for this change the business area did an administrative credit reduction. However the system was not set up to account for this transaction in the subsequent model year report. Now that the reassessment feature is available we will carry out a reassessment to correct the sales number. This will update the the MY2020 report credit reduction. But the admin credit reduction needs to be delete to ensure the transaction page is also correct.

**Acceptance Criteria**
- [ ]  Deletion of 'Administrative Credit Reduction' record in Production
- [ ]  Checking that Toyota transaction and credit balances are correct, given the deletion the 'Administrative Credit Reduction' (AR-1).

**Additional context**
- Reassessment feature had been released to production and will need to be monitored when used for the first time.
- Coordinate with the business area and with Toyota during the reassessment process to verify the updated value is being pulled through.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1711?planning-poker) with Zenhub @AlexZorkin @JulianForeman @prv-proton @tim738745

**Comment by jdon-zev** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalFhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2006c905ab8340a6d06fcce162e08afb93d6f726/AR-1_Toyota.jpg)
