### ISSUE TITLE
ZEVA - text appearing when it shouldn't

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1713]
**Describe the Bug**
The following text is appearing on the Compliance Obligation tab of a model year report for both IDIR and BCeID users; as well as on the assessment tab on a submitted report to idir users.

"Only credits of the same model year of this report can be edited."

This text should only be visible on a supplementary report or reassessment recommendation page.

![text-error.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/ad32da20-103c-475e-965e-f92acb6d7433)

**Expected Behaviour**
When viewing a model year reports compliance obligation page or assessment tab; the text "Only credits of the same model year of this report can be edited." should not be visible.

When viewing a supplementary report or reassessment compliance obligation page this text should be visible.

**Actual Behaviour**
The text appears on a model year report where it shouldn't

**Acceptance Criteria**
- [x] When viewing a model year report the aforementioned text should not be shown.
- [x] When viewing a reassessment or supplemental report this text should be visible.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1713?planning-poker) with Zenhub @AlexZorkin @JulianForeman @prv-proton @tim738745

**Comment by airinggov** [comment]
looks good, closing card
