### ISSUE TITLE
ITVR - Provide NCDA historical application numbers

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1729]
**Describe the task**
We recently updated the information being sent to NCDA via the API to include application numbers. NCDA would now like to receive the historical application numbers from before the API was updated. These can be provided by API or as a spreadsheet.

**Purpose**
The NCDA need to be able to better locate applications, and having the app# as well as the drivers license allow them to do that.

**Acceptance Criteria**
- NCDA receives all application numbers

**Additional Context**
We can give the NCDA a spreadsheet containing all the rebates we've sent to them with application ids associated with each. Can simply download a csv of the go_electric_rebate table (can oc port forward to the prod read-only db, and, using pgadmin, download the results of a select * query on the table).

**Comment by kcabhar** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1729?planning-poker) with Zenhub @AlexZorkin

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1729?planning-poker) with Zenhub @prv-proton @JulianForeman @tim738745 @jig-patel
