### ISSUE TITLE
CTHUB - provide permission to allow users to upload data in test and prod

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1733]
**Describe the task**
Provide CTHUB users with required permissions to all of them to upload data into CTHUB on both prod and test. 

Prod site: https://cthub-prod.apps.silver.devops.gov.bc.ca/
Test site: https://cthub-test.apps.silver.devops.gov.bc.ca/

Users are currently unable to upload any data into CTHUB. When the user attempts a data upload in either the test or prod environment they receive an error message that they do not have the required permission to upload data. User log-in using their email and IDIR. There are no user accounts so there is no need for any permissions to restrict data uploads.

**Purpose**
Users populate much of the data in CTHUB by uploading files. If they are not able to do this the application does not have a key piece of functionality

**Acceptance Criteria**
- [ ] All users with accounts are able to upload data into CTHUB.

**Development Notes**
- From openshift logs on the backend pod in prod. Forbidden: /api/minio/put

**Additional context**
- From context it seems this was working and now isn't, possibly a user token parsing error when uploading data from the gold migration?  There shouldn't be any permission checking on uploading data.  If a user has an account they can upload data.
- Possibility this never worked and there is a permission check that shouldn't be there.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1733?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745 @jig-patel @prv-proton

**Comment by AlexZorkin** [comment]
The user information pr has been merged to test so this work can continue.

**Comment by tim738745** [comment]
@jdon-zev can you please ask the user trying to upload stuff to log in to the test environment (https://cthub-test.apps.silver.devops.gov.bc.ca/) via their idir? Then I can add their keycloak username to the list of whitelisted users allowed to upload things. This would be for the test environment, but I also may be able to get them access in prod without having to repeat the process there; I'll let you know!

**Comment by jdon-zev** [comment]
@tim738745 Jenna has now logged in to test successfully.

**Comment by tim738745** [comment]
@jdon-zev okay, I added Jenna to the list of users allowed to upload stuff; can you ask her to try uploading something in test? If that works, can you ask her to try in prod as well? If it doesn't work in prod, we'll need to do a prod release and repeat the process (i.e. ask her to log in to prod so I can grab her keycloak username).
