### ISSUE TITLE
ZEVA - Write Unit Tests for Organizations

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/zeva#1741]
**Describe the task**
There is a considerable lack of unit tests for Organizations. We aim to fill this gap.

**Purpose**
Adding unit tests will increase the confidence in capturing the business logic and ensure the consistent functioning of the Organizations.

**Acceptance Criteria**

- [ ] Create a new tests directory in the /organizations directory
- [ ] *Pick 3* files and create test files for the components that currently lack coverage
- [ ] Write unit tests to reach 50% coverage in the Components test files
- [ ] Focus on capturing business logic in each of the component files such as calculation logic, user input validation, state changes, etc.

**Additional context**

use the jest --coverage command to view the current coverage percentages for the files

![Screenshot 2023-05-15 at 1.45.45 PM.png](https://images.zenhubusercontent.com/5cdd9741d341f7297326d416/7d16a517-7456-43bb-a0a8-eb687bf6cc0b)

**Comment by jdon-zev** [comment]
No user testing required.
