### ISSUE TITLE
ZEVA - Create Supplementary Report button placement

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1755]
**Title:** Create Supplementary Report button placement

**Description:** Please relocate the Create Supplementary Report and Print Page buttons to the top of page as shown in the mockup

**Wireframe:** 
https://preview.uxpin.com/ba292bb89debd007a79659b3f657c3649ade8efa#/pages/159665032?mode=fm

**Purpose and benefit to user:** This is a more logical and accessible location for these buttons rather than nested within individual reports within the history.

**Acceptance Criteria:**

- [ ] Given I am a bceid user, When I am on an assessed MY report page, then the Create Supplementary Report and Print Page buttons are located at the top of page
- [ ] Given I am a idir user, When I am on an assessed MY report page, then the Create Reassessment and Print Page buttons are located at the top of page

**Development Checklist:**
- [ ] Move the print button to top of the age.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1755?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745

**Comment by airinggov** [comment]
The button placement needs to be outside or separated from the history component, it should a stand alone area at the top of page. Also the Print button is duplicated at times between the old location and new location.

**Comment by airinggov** [comment]
perfect, looks good
