### ISSUE TITLE
ZEVA - Error when analyst tries to submit credit agreement to Director

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1765]
**Describe the Bug**
In the test environment, when an analyst ties to submit a credit agreement to the Director they receive a 'we're sorry' message. It appears to the user that the recommendation has failed.

https://zeva-test.apps.silver.devops.gov.bc.ca/credit-agreements/107

**Expected Behaviour**
The analyst click 'submit to director' for a credit agreement and it fails to submit and the user get a 'we're sorry' error message.

**Actual Behaviour**
The user is given a 'we're sorry' message when they click to recommend a credit agreement to the director.

**Implications**
It is not possible to submit a credit agreement to the Director so credit agreement cannot be issued to suppliers.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Go to https://zeva-test.apps.silver.devops.gov.bc.ca/credit-agreements
2. Click on a draft credit agreement
3. Click to submit the agreement to the Director
4. See error message, and that it has failed to submit to director.

**Dev Notes**
This is a breaking organization reference in the send_email.py file so we just need to rework that bit of logic for this function to work.

**Dev Logs**
File "/opt/app-root/src/api/services/send_email.py", line 255, in get_subscribed_user_emails
Q(organization_id__in=[obj.organization, govt_org.id]) &
AttributeError: 'str' object has no attribute 'organization'
notifications_credit_agreement None

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1765?planning-poker) with Zenhub @AlexZorkin @jig-patel @JulianForeman @prv-proton @tim738745

**Comment by tim738745** [comment]
Fixed as part of zeva card 1783
