### ISSUE TITLE
ZEVA - Re-designed supplier detailed credit balance in creidt transcation page

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1772]
Due to the difficulty of how to display deficit balances in the current credit transaction and balance page, plus the growing list of transaction suppliers are building up, we want to redesign the credit transaction page:

IDIR - https://zeva-test.apps.silver.devops.gov.bc.ca/organizations/2/credit-transactions

BCeID - https://zeva-test.apps.silver.devops.gov.bc.ca/credit-transactions

As a result this will avoid the need to re-design the detailed credit balance component displayed on these pages. This involves displaying three elements of the credit balance information separately.
1. Credits they have obtained or current compliance period 
2. Credit compliance position from the last model year reassessment
3. Total detailed credit balance if they had a positive credit balance at the end of the last compliance period (or no detailed balance if they were in a deficit at the end of the last compliance period)

Positive Balance
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/160856647/simulate/no-panels?mode=mf
Deficit balance
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/161518599/simulate/no-panels?mode=mf 

**Purpose and benefit to user:**
This redesign of the detailed credit balance makes it clear to the user the:
- Credits they have obtained or current compliance period 
- Credit compliance position from the last model year reassessment
- Total detailed credit balance if they had a positive credit balance at the end of the last compliance period (or no detailed balance if they were in a deficit at the end of the last compliance period)

**Acceptance Criteria:**
Given I am a ZEVA user (IDIR or BCeID)
When I am viewing the credit transactions page for an organization
Then I want to see the re-designed detailed balance table as per the mock ups

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by kcabhar** [comment]
Tim estimates 3 going into Klefki
