### ISSUE TITLE
ZEVA - Update error message 

### ISSUE THREAD

**Issue by Kailee-Douglas** [bcgov/zeva#1782]
**Describe the task**
Currently, the error message in ZEVA says, "We are sorry. It looks like our system is experiencing some technical difficulties. We have been notified and will look into it. Please try again later." Our team is not actually notified when there is an error.

Action: Update existing error message to "We are sorry. It looks like our system is experiencing technical difficulties. Please try again later."

**Purpose**
Because our team is not actually notified when there is an error, this is untruthful, misleading, and a poor user experience.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

Development checklist:
- Change the messages as mentioned above in StatusInterceptor.js file

**Additional context**
TFRS also has the same error message and a ticket has been created for it.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1782?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745
