### ISSUE TITLE
ZEVA - persistent error messages and log-outs across the app

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1783]
**Describe the Bug**
IDIR and BCeID users are frequently reporting issues where they perform an action in ZEVA (prod and test) and receive a 'we're sorry' message, or they are re-directed to the log in screen as if the system has logged them out.

Reports of this behavior include:

1. When the Director issues a credit application.
2. When the Director issues a credit agreement.
3. When the Director issues a model year assessment.
4. When the Analyst recommends a credit application to the Director.
5. When the Analyst tries to save a model year assessment.
6. When the Analyst tries to filter a credit application for a particular error code (this is the attached example which shows the console info - it occurred around 2:10PM on June 7th)

**Expected Behaviour**
The app should work such that users do not get random and unexpected error messages, or be re-directed to the log-in screen, when they are using the app.

**Actual Behaviour**
Users performing a variety of basic action in ZEVA receive error messages or are redirected to the log-in screen.

**Implications**
User do not know if the action they have performed were successful, and find working in ZEVA overly time consuming and frustrating as they regularly have to navigate back to the page they were working on or reload the app.

**Steps To Reproduce**
Steps to reproduce the behaviour: Reproducing these errors is difficult as they do not happen consistently. There seems to be a random element to this issue.
User/Role:

**Comment by jdon-zev** [comment]
![image.png](https://images.zenhubusercontent.com/63c843041aa7297691df71de/d05e61f5-e42f-401e-9e63-77bd0113f82d)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1783?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745

**Comment by tim738745** [comment]
1	When the Director issues a credit application. - could not recreate - possibly fixed by card 1614
	2	When the Director issues a credit agreement. - fixed
	3	When the Director issues a model year assessment. - could not recreate - possibly fixed by card 1614
	4	When the Analyst recommends a credit application to the Director. - could not recreate - possibly fixed by card 1614
	5	When the Analyst tries to save a model year assessment. - could not recreate - possibly fixed by card 1614
	6	When the Analyst tries to filter a credit application for a particular error code (this is the attached example which shows the console info - it occurred around 2:10PM on June 7th) - fixed

**Comment by tim738745** [comment]
1	When the Director issues a credit application. - could not recreate - possibly fixed by card 1614
	2	When the Director issues a credit agreement. - fixed
	3	When the Director issues a model year assessment. - could not recreate - possibly fixed by card 1614
	4	When the Analyst recommends a credit application to the Director. - could not recreate - possibly fixed by card 1614
	5	When the Analyst tries to save a model year assessment. - could not recreate - possibly fixed by card 1614
	6	When the Analyst tries to filter a credit application for a particular error code (this is the attached example which shows the console info - it occurred around 2:10PM on June 7th) - fixed

**Comment by jdon-zev** [comment]
Not possible to effectively test. Card to be closed and app to be monitored for continuing problems.
