### ISSUE TITLE
ZEVA -  "Save/Recommend" Functionality Issue on Model Year Report

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1787]
**Describe the Bug**
As an IDIR analyst, while attempting to save or recommend a MY Report to the director, an error is encountered that prevents the action from being completed.
![myr-save-rec-error.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/e0bd2d65-ebfc-4f0f-bf9f-95fbabd577e5)

**Expected Behaviour**
An IDIR analyst should be able to save and recommend a MY Report without encountering any error.

**Actual Behaviour**
An error message is displayed when an IDIR analyst attempts to save or recommend a MY Report.
The specific error message can be seen in the attached screenshot.

**Implications**
As an IDIR analyst, the inability to save or recommend MY Reports impedes the report processing, which might delay critical decisions or actions that need to be taken by the director.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR Analyst
1. Go to the "Reports" section and find a MY Report that is in 'Submitted' status.
2. Open the report and scroll down to the compliance position section.
3. Select a radio button to indicate the compliance position.
4. Click on either the "Save" or "Recommend" button.
5. Observe the error message that is displayed (as shown in the attached screenshot)

**Notes**
Investigate in the server logs what is causing the internal server error 500

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1787?planning-poker) with Zenhub @AlexZorkin @jig-patel @prv-proton @tim738745

**Comment by tim738745** [comment]
Fixed as part of the email fixes card for zeva (card 1709)
