### ISSUE TITLE
ZEVA - Avoiding user error for backdating credits issued with model year assessments

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1790]
**Problem Description** 
**In order to** avoid users failing to remember to check the box to back date credits (submitted with a model year report), zeva **needs to** better manage the credit application process during the model year reporting process for credits of the same model year as the report.

**Solution Needs**
- It must be possible to differentiate between different model year credits so only the relevant ones are back dated
- There must be no possibility of human error leading to credits being issued incorrectly in terms of their date of issuance.

**Timebox**
- Two days

**Outcome**
Details describing the outcome of the research 
- Review the proposed solution in card #1652 (currently blocked) 
- Recommend a way forward, and the work required, to solve the issue

**Additional Context**
- Going to need to dive into the database again to see how connected these pieces are.  The less connected, the more difficult it will be to automate.
- 100% certain that the credit transaction table is standalone, it has no foreign keys and no way to compare entries to anything if we need to.
- This is also going to require lots of date checking so we need to make sure we are using the correct timestamp for each related table
- This work will also require more time working with the business area for specifics.

**Comment by AlexZorkin** [comment]
There is a period of time between when a model year report has been submitted and when it actually gets assessed. In this period the supplier can upload additional sales submissions which could potentially alter the credits issued at the time of assessment. We need to add some additional business logic to automatically back date sales to Sept. 30th of the model year for vehicles in that model year. If vehicles are uploaded that have a model year later than the current open assessment period, then they need to be assigned a new warning “71” which is “Model year cannot be issued with an active compliance report”.

Development Requirements:

- add new warning 71 to frontend app/constants/errorCodes.js to match new backend warning property 71
- sales_submission_content model @property def warnings(self): will need logic to account for warning 71
- Review SalesSubmission update method to ensure the RecordOfSale logic still works with warning 71
- On Sales Submission create/update, write business logic similar to the following sudo code to ensure only the vehicles from the correct model year are added as pending credits:

IF OPEN MYR STATUS == [‘SUBMITTED, RECOMMENDED, or RETURNED]
	IF CURRENT REAL DATE > compliace_year_sept_30 + 1 year
		IF CURRENT REAL DATE > compliace_year_oct_30 + 1 year
			NO ACTION ALLOWED, beyond applicable dates
		ELSE IF CURRENT REAL DATE < compliace_year_oct_30 + 1 year
			action allowing credits for vehicles within that model year, but set their effective date to Sept30, all other vin entries get a 71 warning flag (may need to set snapshot)
	ELSE IF CURRENT REAL DATE < compliace_year_sept_30 + 1 year
		ISSUE all credits as of the processing date

**Comment by jdon-zev** [comment]
Alex, I have a couple of comments on what you've written on this.
1. For sales to be eligible to be backdated they must be both the same model year as the report and have been submitted prior to the model year report being submitted to government. 
2. The 71 error code should apply to any sales that are not of the same model year as the report. That would include both later model years and earlier ones.

**Comment by AlexZorkin** [comment]
Some additional notes:

The problem:
When a model year report is submitted for model year 20xx
It includes the credits from all ZEV sales that have been submitted to government of model year 20xx but have not yet been issued (shown as pending credits)
These pending credits need to be backdated when they are issued so that the supplier has these credits in their account on the compliance date of Sept 30th (of the calendar year prior to model year 20xx)
 
Credits should be backdated when:
They are part of a credit application in submitted status
And a model year report has subsequently been submitted to government 
And the credits are of the same model year as the submitted model year report
Otherwise, they should be tagged as 71 error and not issued.
