### ISSUE TITLE
ZEVA - IDIR opening a credit application error

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1805]
**Describe the Bug**
IDIR analyst is receiving the attached error when opening a credit application in production
![ca-open-error.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/cad3f429-a697-4975-8ac0-1705145c315a)

**Expected Behaviour**
A credit application should open without error in order to process it

**Actual Behaviour**
IDIR analyst receives an error when opening the credit application from the index page. It is an application with only one VIN record. Other applications open fine.

**Implications**
IDIR analyst can't process the application to verify with ICBC data and recommend to the director.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir\analyst
1. In ZEVA production go to the credit application index page and click CA-431
2. See error

**Comment by tim738745** [comment]
@jdon-zev @airinggov @AlexZorkin I took a closer look; seems like Alex you committed a fix for this 3 weeks ago (https://github.com/bcgov/zeva/commit/43f3ab81c1827bf6d883db579aa5835cdc690508#diff-80bdafa3fdb2432977dfdd69af5dae812e2af994533f6ad2257f60238a25ad61)? So I think we can close this; it just needs to be pushed to prod. If this is urgent, we can probably do a hotfix push to prod with just this change; let me know what you guys think!

**Comment by jdon-zev** [comment]
Not possible to test this. Card to be closed.
