### ISSUE TITLE
ZEVA - MY Reports for Small Suppliers

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1807]
**Title:** MY Reports for Small Suppliers

**Description:**
ZEVA can’t presently support MY reporting for small suppliers. The Compliance Obligation tab doesn’t support the logic of a small supplier not having an obligation or resulting credit reduction. It currently defaults to calculate a credit reduction using the medium supplier requirements.

Update the Compliance Obligation tab to recognize that small suppliers don’t have compliance obligation. 

1.	Set both the “Compliance Ratio Credit Reduction” and “Unspecified ZEV Class Credit Reduction” to: 0.00
2.	For the radio selection “Do you want to use ZEV Class A or B credits first for your unspecified ZEV class reduction?”, either default the radio selection to B and lock it or hide the selection completely.

**Wireframe:** <link>
![small-myr.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/fdbec53d-474c-440a-9272-6b781167f736)

**Purpose and benefit to user:**
This will enable small suppliers to submit MY reports accurately. 

**Acceptance Criteria:**

- [ ] Given I am a BCeID user of a small supplier, When I am creating a MY report, then I can report my LDV sales and have an accurate report with no credit reduction applied.

**Development Checklist:**
- [ ] Check if the logic for small suppliers exists for this functionality if not, add it by referring above.
- [ ] Ensure there is logic to check for a small supplier on MY reports. (This may require some business logic input)

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1807?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745

**Comment by tim738745** [comment]
@airinggov @jdon-zev when testing, please also test creating MYRs for medium + large suppliers to make sure nothing on that front has been affected. Also, we'll need to make a card to handle reassessments for small suppliers.

**Comment by airinggov** [comment]
can these two vales be set to zero?
![image.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/304c739b-4f82-4668-ad32-5f1a634cb113)

**Comment by airinggov** [comment]
like the Compliance Obligation tab display?
![image.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/42064af0-b5c3-4d9d-aef6-b82c13d86b28)

**Comment by tim738745** [comment]
@airinggov sure; which tab is this?

**Comment by airinggov** [comment]
the first is the Summary tab, second is the Compliance Obligation tab

**Comment by jdon-zev** [comment]
Tim, as mentioned in the sprint review I'd like to remove the text and credit type selection piece that is currently under the credit reduction section heading. Would like to replace with some text. Al will provide a mock-up but we thought this could be another card?
