### ISSUE TITLE
ZEVA - Count of warnings in ICBC check is incorrect

### ISSUE THREAD

**Issue by jdon-zev** [bcgov/zeva#1809]
**Describe the Bug**
The count of warnings when a credit application VINs are checked against ICBC data is incorrect. This is evident in production.

Please note this bug was already fixed in a previous ticket.

**Expected Behaviour**
The number of errors should be added up correctly and displayed in the drop down. In this example the drop down says there are 3 warnings in total but as can ben seen in the screen shot there are 9.

**Actual Behaviour**
See above.

**Implications**
The analyst has to manually count the number of warnings rendering the count in the drop down useless.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR Analyst
1. Go to Credit transactions
2. Click on A credit application and click to review the details.
3. Look at drop down of errors and see number of warning in brackets.
4. See incorrect figures.

![Incorrect warning numbers again.jpg](https://images.zenhubusercontent.com/63c843041aa7297691df71de/34a0893d-d513-498b-8996-ae0b72d7747f)

**Comment by kcabhar** [comment]
Revisit when ticket 1469 is complete - will make counting easier

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1809?planning-poker) with Zenhub @AlexZorkin @tim738745

**Comment by JulianForeman** [comment]
I think this will be fixed as part of the saving credit application errors/error 71 work.

**Comment by tim738745** [comment]
PR build: https://zeva-dev-1978.apps.silver.devops.gov.bc.ca/
