### ISSUE TITLE
ZEVA - Negative zero bug in MY report reassessment

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1832]
**Describe the Bug**
When viewing the reassessment recommendation page for a MY Report that includes transferred away credits, zero values are incorrectly displayed as "-0.00" in the input box. This is a display error, as zero should not be shown with a negative symbol. This issue likely arises from a default symbol configuration for transferred away credits, which are typically shown in the negative. However, the symbol should only appear when there's an actual amount above zero. This bug also appears in the Supplementary Report in the "Administrative Credit Reduction" section.

**Expected Behaviour**
Zero credit values should be properly displayed as "0.00", without any negative symbol.

Note: this also showed up in Supplementary Report as shown in second screen capture, Administrative Credit Reduction.

**Actual Behaviour**
Zero credit values are incorrectly shown as "-0.00".

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/25055ced-e6d8-4c69-bb52-ec2b96f4a78c)

![negzero.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/d132f01b-5cd5-4870-9b5c-7e05628f2f09)

**Implications**
This display bug may lead to confusion or misunderstanding among users, potentially disrupting their workflow or leading to incorrect reporting.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir\analyst

1. Log in to the system using idir\analyst credentials.
2. Navigate to a MY Report reassessment that includes transferred away credits (e.g., PAC 2020).
3. Click on the "Reassessment Recommendation" tab.
4. Observe the incorrect display of zero values in the credit amount input box.

Debugging Notes:
Please review the code responsible for displaying transferred away credits, specifically the function or formatting rule that is adding the negative symbol. It's possible that the sign is being added by default to all values, including zero. Adjust the logic so that the negative sign only appears for values above zero.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1832?planning-poker) with Zenhub @AlexZorkin @tim738745
