### ISSUE TITLE
ZEVA - Vehicle Supplier navigation tabs

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1833]
**Describe the Bug**
As an idir user when I am on the Vehicle Suppliers index page, if I select a supplier from the list and then immediately click a tab on the resulting page before it loads completely I will receive a We're Sorry error.

It appears the navigation bar links haven't completely loaded to include the proper supplier ID reference and so has a null.

https://zeva-dev.apps.silver.devops.gov.bc.ca/organizations/null/credit-transactions

**Expected Behaviour**
As pages can be slow to load it would be nice if I could click a link and have it work properly without having to wait.

**Actual Behaviour**
If I click too quickly on a link I will receive an error and then I have to refresh the page.

**Implications**
It's an annoyance for navigating. Perhaps there is a simple fix to build the URLS so they render at the same time as the navigation tabs.

**Dev Checklist**
- [ ] Pass necessary data to the url to be able to navigate through vehicle supplier tabs without waiting for the page to load

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir
1. Go to Vehicle Suppliers index page and select a supplier,
2. Click on any of the links in the navigation tabs before the page builds completely
3. See error

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1833?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745

**Comment by airinggov** [comment]
Love it
