### ISSUE TITLE
ZEVA - Set suppliers first MY Report

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1837]
**Title:** Set vehicle suppliers first MY Report year

**Description:** The current system forces new suppliers to start with a 2020 report. We need to support suppliers creating their first report in the year they started selling vehicles in BC. 

As an IDIR Analyst I require the ability to set a new suppliers first MY Report year. Once a supplier has a MY Report  submitted to government or assessed this would be locked from being updated.

The drop down should have selections from 2020 to current year.

**Wireframe:**
https://preview.uxpin.com/246954456c24001734137c07f930e2a511a1d7c6#/pages/163849644?mode=fm

https://preview.uxpin.com/246954456c24001734137c07f930e2a511a1d7c6#/pages/163850251?mode=fm

**Purpose and benefit to user:** This will stop 2020 being the default report year. It will allow government to set the first report year. It will prevent errors if this was left to the supplier to select.

**Acceptance Criteria:**

- [ ] Given I am a IDIR\Analyst, when I am entering a new supplier, then I can set the year for their first MY Report

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

When a supplier clicks the New Report button the logic used to determine what year to create will need to be updated. e.g. does supplier have an existing assessed report, if yes increment 1 year from latest year report; if no, use the date set by this new update.

Existing suppliers will need this new date set to 2020

**Acceptance Criteria**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1837?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745

**Comment by AlexZorkin** [comment]
Waiting for wireframe from @airinggov

**Comment by airinggov** [comment]
The drop down should have years 2020 to current year. It is displaying years 2017, 2018, 2019 in error.

The drop down should be locked once the supplier has a report created in any status. Above it stated to be locked when Submitted or Assessed but it should be locked if they have a report in any status.
