### ISSUE TITLE
ZEVA - Supplementary Report Save button for director

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1838]
**Describe the Bug**
As a director looking at a supplementary report in recommended status looking at the Supplementary Report and Recommendation tabs, there is a Save button appearing. It is the Save button from the Reassessment tab but it should not appear on any of the other tabs.

**Expected Behaviour**
The Save button should only appear on the Reassessment tab as a director.

**Actual Behaviour**
The Save button appears on all tabs.

**Implications**
A clear and concise description of any implications.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir\director
1. Go to a recommended Supplementary Report
2. Click on all 3 tabs
3. Scroll down to bottom to see Save button on all tabs

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1838?planning-poker) with Zenhub @AlexZorkin @tim738745
