### ISSUE TITLE
MY Report assessments/reassessments default open

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1840]
**Describe the Bug**
Assessed MY Reports assessments/reassessments should open to the most recent assessment or reassessment. 

**Expected Behaviour**
For all users, reports should open to the most recent assessment or reassessment. 

**Actual Behaviour**
Reassessed reports opens properly from the MY Report index page but not from the Credit Transaction page where it opens to the original assessment.

**Implications**
This can be confusing if the numbers don't align and you don't realize you are not on the most recent reassessment.

**Acceptance Criteria**
- [ ] When clicking a model year report from the credit transaction page that has been reassessed it should send you to the reassessment, not the original assessed report.

**Dev Checklist**
- [ ] Change get request to send users to the most recent assessed supplementary or reassessment from the credit transaction page

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1840?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745
