### ISSUE TITLE
ZEVA - Unable to save new Model Year report

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1841]
**Describe the Bug**
Users can initiate the creation of a new MY Report, however, when they attempt to save the report using the "Save" button, no action is taken. The button appears to be non-responsive only for new reports.

**Expected Behaviour**
When creating a new MY Report, the "Save" button should successfully save the report as a draft, allowing the user to revisit and complete it at a later time.

**Actual Behaviour**
While the "Save" button functions correctly for existing draft reports, it does not respond when used for a new report, failing to save the newly created report.

**Implications**
This bug significantly disrupts the workflow of suppliers, as they are unable to create and save new MY Reports. This could potentially delay compliance reporting and affect overall operational efficiency.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: bceid\ZEVA User

1. Log in to the system using bceid\ZEVA User credentials.
2. Navigate to the "Compliance Reporting" section.
3. Click on the "New Report" button to create a new MY Report.
4. After entering the required details for the report, click on the "Save" button.

**Debugging Notes:**
Please check the event handlers attached to the "Save" button, specifically when creating a new report. There may be an issue with the button's onClick event, or there might be an error preventing the save function from executing successfully for new reports. Additionally, verify that the permissions for bceid\ZEVA User role allow for the creation of new reports.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1841?planning-poker) with Zenhub @AlexZorkin @tim738745
