### ISSUE TITLE
ZEVA - React tables - server side pagination

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#1842]
**Title:**
React tables - server side pagination

**Description:**
Some pages/views within ZEVA that use React Table may load quite slowly, due to the fact that it loads all the data at once. To improve performance, we should implement server-side pagination on one of these pages. Please choose a page from the list below:

BCeID
Compliance Reporting
Credit Applications, Transfers
ZEV Models
Administration
• Users

IDIR
Compliance Reporting
Credit Applications, Transfers, Agreement
ZEV Models
Vehicle Suppliers
• Users
Administration
• Users

**Purpose and benefit to user:**
Faster loading pages will make for a better user experience.

**Acceptance Criteria:**

- [ ] Given I am a user, when I navigate to the page where server-side pagination was implemented, the data that loads should be only the data that I see on that page. Also, navigating between the pages should work as expected, and efforts should be made to preserve filtering/sorting behaviour.

**Development Checklist:**
- [ ] Choose a page containing a React Table from the list above.
- [ ] Set up the front end state tracking fields (e.g. pageNumber, filters, sorts, etc) and make the React Table a controlled components dependent on those fields
- [ ] Implement a backend endpoint that can receive a paginated data request, and return the appropriate response
- [ ] If it's not feasible to filter/sort against certain fields in the React Table under this new scheme, seek feedback from the product owner or UI/UX designer.

**Notes:**
Can see zeva card 1613 for an example of what to do.

**Comment by JulianForeman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1842?planning-poker) with Zenhub @AlexZorkin @tim738745
