### ISSUE TITLE
ZEVA - New security role

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1849]
**Describe the Bug**
A new user role has appeared 'Manage ZEV'

![managezevrole.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/03d41b4c-249e-40c1-b9d3-3e2119f18dff)

**Expected Behaviour**
This role should not exist, the function is part of the ZEVA User role.

**Actual Behaviour**
The BCeID user admin page now has a 4th role to Manage ZEV, it should not be there.

**Implications**
Additional role is not required.

**Dev Checklist**
- [ ] Check openshift pod in production to see if this extra role exists in the roles table there.
- [ ] Check main branch for code surrounding this role
- [ ] Remove extra role from dev/test and snapshot databases if it does exist there.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCEID\Organization Administrator
1. Go to Administration tab
2. Click on an existing user or New User
3. See new user role

**Notes**
Currently, this role only appears in the dev environment; this is probably just a data issue (need to remove this role from the role table)

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1849?planning-poker) with Zenhub @AlexZorkin @tim738745

**Comment by tim738745** [comment]
The "Manage ZEV" role is not in the prod database, and as far as I can tell, nothing in the upcoming deployment to prod will add that role. There is a fixture from some time ago that adds this role (amongst others), and that's probably why it's there in Dev and Test; it could be the case that it, and its dependencies, were manually deleted from prod.

**Comment by airinggov** [comment]
@tim738745 can we remove the Manage ZEV role from dev and test?

**Comment by tim738745** [comment]
@airinggov I cleaned it up; you shouldn't see that role anymore on test or dev

**Comment by airinggov** [comment]
@tim738745 thanks Tim, I guess we'll have to do that in Julian's test data too
