### ISSUE TITLE
ZEVA - Allow BCeID user to delete Draft MY Report

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1852]
**Title:**
Allow BCeID user to delete draft MY Reports. 

**Description:**
Add Delete button to all 4 tabs of report when in Draft status.. This will have a modal confirmation:

Text: Do you want to delete this report?
Buttons: Cancel | Delete

**Wireframe:** 
https://preview.uxpin.com/ba292bb89debd007a79659b3f657c3649ade8efa#/pages/139325952?mode=fm

**Purpose and benefit to user:**
A supplier can delete a report.

**Acceptance Criteria:**

- [ ] Given I am a BCeID\Zeva User, I can see and use a delete button across all tabs of a Model Year Report in draft status
- [ ] The delete report button has a modal to confirm the action

**Development Checklist:**
- [ ] Validate any and all data created by the draft report is also deleted from the database, no ghost records

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1852?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745

**Comment by airinggov** [comment]
@tim738745 receive the We're sorry error after deleting as the redirect URL stays on the report
https://zeva-dev.apps.silver.devops.gov.bc.ca/compliance/reports/151/supplier-information

It should redirect back to the Compliance Report index page

**Comment by airinggov** [comment]
it didn't actually get deleted either. But this was after the report being submitted to gov, edits made by the analyst, then the report being Returned, so set back to draft.

**Comment by tim738745** [comment]
@airinggov I fixed it; please have another look on dev when you get a chance

**Comment by airinggov** [comment]
@tim738745 looks great, thanks Tim
