### ISSUE TITLE
ZEVA - MY Report History bugs

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1863]
**Describe the Bug**
This history is almost completely wrong. Double transactions showing, it was never returned. It couldn't be returned by Ford as shown. It doesn't match original snapshot data. Nothing was changed on this report so the history shouldn't have changed.

![history-bugs.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/805b7a63-207c-4d15-a561-23449c7092fb)

**Expected Behaviour**
When viewing a model year report, the history component should show the correct history entries and no duplicate values.

**Actual Behaviour**
Sometimes a model year report's history will show the same history entry twice.

**Developer Checklist**
- [ ] Decipher if is this an incorrect data issue or potentially a reproducible bug under the right circumstances.
- [ ] Either fix the data issue causing this duplicated entry or modify the code to ensure it can't happen while maintaining correct history.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1863?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745

**Comment by airinggov** [comment]
Still looks like there is an issue here. I don't recall if this report was actually returned (I don't think so). But if it had, the Returned line should probably be tagged to Al Ring (not Dev Ford) then there would need to be a second Signed/Submitted line.

![myrhist.PNG](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/2415c698-4a3a-4f54-bb6e-8e935bbf10a5)

**Comment by JulianForeman** [comment]
This should be fixed with the latest update and snapshot changes. If it persists let me know and I will look into it again.

**Comment by airinggov** [comment]
there is a missing line here, the second supplier sign & submit

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEFVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d27c3fa2496f91a80ef6538a4b66dea5a6847e2/image.png)

**Comment by airinggov** [comment]
we will continue this work with card 1902 so can close this card
