### ISSUE TITLE
ZEVA - report history

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#1868]
**Describe the Bug**
It looks like certain reassessments/supplementary reports are being excluded from the report history.

**Expected Behaviour**
I expect to see an accurate timeline of reports.

**Actual Behaviour**
There is a case where the most recent reassessment does not appear in the timeline.

**Implications**
This may confuse some users.

**Steps To Reproduce**
At the time of this writing: on dev, as a government user, go to Ford's 2021 reports. By **navigating** to the topmost (most recent) entry in the timeline, one will see a report that is not, in fact, the most recent report (which is supposed to be an assessed reassessment with a balance of 1598.88 A credits, and 0 B credits). Note that upon first landing on the page, you will see the correct report; it is only by navigating to a different entry then navigating back will one see a report that one should not be seeing.

**Notes**
I think this is a a backend issue; see the supplemental_history endpoint in viewsets/model_year_report.py. There is some logic in there concerning which supplemental reports to exclude that should probably be reviewed. Also, in SupplementalReportSerializer in serializers/model_year_report_noa.py, there is some logic about how to display the status of a supplemental report that should also be reviewed.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1868?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745
