### ISSUE TITLE
ZEVA - MYR for small suppliers - new text

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#1872]
**Describe the task**
When a small volume supplier is creating a MYR, they shouldn't see the credit selection radio buttons under the compliance obligation tab. Instead, they should see, in its place, some text (to be provided).

**Purpose**
This task adds value by making parts of the reporting process more clear for small suppliers.

**Acceptance Criteria**
- [x] Remove the credit selection radio buttons under the compliance obligation tab for small suppliers.
- [x] In its place, add text: Small volume suppliers have no compliance obligation or credit reduction.

https://preview.uxpin.com/ba292bb89debd007a79659b3f657c3649ade8efa#/pages/163911189?mode=fm

**Comment by tim738745** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1872?planning-poker) with Zenhub @tim738745 @JulianForeman @AlexZorkin

**Comment by airinggov** [comment]
I'm not seeing the change here, try log on to test using tvolvo

**Comment by tim738745** [comment]
@airinggov I thought I merged it but I didn't; I'll get it onto dev and test

**Comment by airinggov** [comment]
@tim738745 okay thanks. Also, we have been doing most the final testing on test, not dev

**Comment by airinggov** [comment]
Work for this card looks good. There is still some work to complete on the IDIR side for assessing small volume supplier reports but this will be a new card.
