### ISSUE TITLE
ZEVA - Handling Deficits in MY Report Compliance Obligation Tab Balance Before Credit Reduction

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1875]
**Description:** 
In the Compliance Obligation tab of the MY Report, the Balance Before Credit Reduction does not currently account for a deficit starting balance. It should, however, treat deficits in the same way as credit reductions, using the oldest credits first to offset the deficit. The types of credits used (A or B) should correspond to the selections made in the current MY Report.

**Wireframe:** <link>
https://preview.uxpin.com/ba292bb89debd007a79659b3f657c3649ade8efa#/pages/140541747?mode=fm

**Purpose and benefit to user:**
By accounting for the starting deficit in the Balance Before Credit Reduction, the system ensures accurate tracking and use of credits.

**Acceptance Criteria:**

- [ ] As a BCeID or IDIR ZEVA user, when viewing the Balance Before Credit Reduction on the Compliance Obligation tab, the system should automatically offset any starting deficit using the appropriate credits (A for A and Unspecified, B for Unspecified only), according to the selections made in the current MY Report.

**Development Checklist:**
- [ ] Modify the calculation for Balance Before Credit Reduction to account for a deficit starting balance.
- [ ] The system should use the oldest available credits first to offset the deficit.
- [ ] Ensure that the correct types of credits are used according to the current MY Report selections (A or B).
- [ ] Implement appropriate unit tests to verify this functionality.

**Notes:**
Please refer to the provided wireframe for more visual context. Further clarification may be needed to confirm how to handle situations where there are not enough credits to cover the entire deficit.

**Comment by tim738745** [comment]
@airinggov @jdon-zev extensive testing needed here; I added the Create PR Build tag. More remarks to follow!

**Comment by tim738745** [comment]
PR build link: https://zeva-dev-1958.apps.silver.devops.gov.bc.ca/

**Comment by tim738745** [comment]
@airinggov @jdon-zev when testing, please make sure to test, for both BCeID and IDIR users, for each class of supplier, for MYRs, Supplementaries and Reassessments that start with a deficit and those that don't: that their reductions and balances (basically all the numbers) are correct on all of: the compliance obligation tab, the summary tab, and assessment tab, and that the numbers are updated accordingly when a BCeID user make a credit offset selection, and that the correct changes to credit transactions are made when a MYR/Supplementary/Reassessment gets issued.

**Comment by tim738745** [comment]
@airinggov @jdon-zev please also remember to test cases where credits can cover the deficit, and cases where they can't (in the latter case, remaining deficits should carry over)

**Comment by airinggov** [comment]
Looks good. One issue is that a supplier can put themselves in and out of deficit based on the A/B selection. Also not sure if the older B credits are being reduced in the correct method.
