### ISSUE TITLE
ZEVA - Credit Application processing, new Error 71

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1878]
**Title:** New Error 71 for Credit Application processing with a MY Report

**Description:** Error 71 is a new error check run when processing a credit application when a supplier also has a MY Report submitted. It is only run when the checkbox is selected (card 1879). It will only allow model year VIN that match the year of the MY Report to be validated. VIN that are of a different year are a 'critical' error, meaning they cannot be validated. No checkbox is provided for the analyst to override the warning and issue the sale. These VIN errors will also need to be added the the error download provided to the supplier after the CA has been processed. The error will display in the drop down menu as "71- Wrong model year for compliance report". This is the text to be included in the error download: "Wrong model year to be issued with compliance report"

**Wireframe:** <link>
https://preview.uxpin.com/246954456c24001734137c07f930e2a511a1d7c6#/pages/137034674?mode=fm

**Wireframe: (From previous 1879)** <link>
https://preview.uxpin.com/246954456c24001734137c07f930e2a511a1d7c6#/pages/163900833?mode=fm

**Purpose and benefit to user:** This will reduce the likelihood of validating credits in error and reduce manual work for the analyst of having to interact with a checkbox.  

**Acceptance Criteria:**

- [x] Given I am a IDIR analyst, when I am processing a CA as part of a MY Report, then any VIN of the wrong model year will be automatically excluded from being issued.
- [x] Given I am a BCeID ZEVA User, when I am looking at a CA that was issued with 71 Errors, then I can download those in the Excel file so I can resubmit them at a later date.

**Development Checklist:**
- [x] Add new error type 71 in the database
- [x] Change backdating checkbox to new alert (see wireframe) that is displayed and default checked if a model year report is in progress
- [x] Do not show alert at all if there is no model year report in progress
- [x] If the checkbox for backdating is unchecked then disable the submission button until the existing report is processed
- [x] Create logic to check vehicle model years to ensure that vehicles outside the report's compliance period when the backdate checkbox is checked are tagged with the new error automatically and don't have their credits issued
- [x] Double check that the new error is a 'critical error' meaning it cannot be changed by any means by an analyst, no checkbox or validation needed.
- [x] Ensure when downloading supplier error excel spreadsheet it includes the new error code.

**Notes:**

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1878?planning-poker) with Zenhub @JulianForeman

**Comment by JulianForeman** [comment]
Dev Link: https://zeva-dev-1932.apps.silver.devops.gov.bc.ca

**Comment by airinggov** [comment]
@JulianForeman  I don't think I have a profile set up here with my idir

**Comment by tim738745** [comment]
PR build: https://zeva-dev-1978.apps.silver.devops.gov.bc.ca/

**Comment by jdon-zev** [comment]
We tested this on Friday. When we submitted a credit application and model year report, all the VINS in the credit app had a 71 error warning. Even those that were the same vehicles of the same model year as the report.

**Comment by tim738745** [comment]
@jdon-zev I fixed the issue and it's on dev now (the PR build)

**Comment by airinggov** [comment]
Error 41 is not being flagged consistently.
The Comment to the Director feature that normally appears after Validation is missing completely.

**Comment by airinggov** [comment]
the analyst recommendation blue panel doesn't reflect the proper VIN number being recommended for issuance

**Comment by shayjeff** [comment]
We will create a new card for the issue above and close this card.
