### ISSUE TITLE
ZEVA - Credit Application processing, MY Report in Progress alert

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1879]
**Title:** New Alert when processing a Credit Application with a MY Report

**Description:** When an analyst opens a credit application to process, perform a check to see if the supplier has a MY Report in submitted status. (Supplemental reports can be ignored from this check).

If yes, include a new alert under the comment block with the following text (the year indicated should match the year of the submitted/pending MY Report).

Model Year Report in Progress  — [supplier name] has a [year] Model Year Report submitted to government and not yet assessed. 

Issue credit application backdated to Sept. 30 as part of their Model Year Report. Only [year] vehicles can be issued, others will be tagged as error 71.

The current 'Issue at Sept 30" checkbox will be removed from the blue area and moved to this alert. The checkbox will default to be selected. This checkbox causes the transaction to be issued as backdated to Sept. 30 [MY Report year+1]. The checkbox will also trigger the error 71 validation check to be run when verifying the CA with ICBC data.

If the analyst deselects the checkbox  the Recommend Issuance button should be disabled with a hover pop-up stating that "This credit application cannot be recommended until the pending model year report is assessed." (The analyst can still verify the CA with ICBC data and save any configuration changes).

**Wireframe:** <link>
https://preview.uxpin.com/246954456c24001734137c07f930e2a511a1d7c6#/pages/163900833?mode=fm

**Purpose and benefit to user:** This will reduce the likelihood of issuing credit applications at the wrong date with MY Reports .

**Acceptance Criteria:**
- [ ] Given I am a IDIR analyst, when I am processing a CA as part of a MY Report, then the application will be issued at Sept. 30.

**Development Checklist:**
- [ ] A
- [ ] B
- [ ] C

**Notes:**

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1879?planning-poker) with Zenhub @JulianForeman
