### ISSUE TITLE
ZEVA - Assessment Tab Starting Balance Doesn't Refresh Correctly After Resubmission

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1888]
**Describe the Bug**
The starting balance in the Assessment tab does not correctly refresh under a specific scenario: when an IDIR analyst returns a MY Report to the supplier for resubmission. The issue may lie in the creation of an assessment snapshot when IDIR opens the report the first time. When the report is returned, resubmitted by the supplier, the assessment does not refresh with the new data.

**Expected Behaviour**
When a report is returned by the analyst and resubmitted by the supplier, the Assessment tab should be reloaded with the newly submitted data.

**Actual Behaviour**
After the report is resubmitted, the Assessment tab retains the initial starting balance instead of updating it to the new one, based on the resubmitted data.

**Implications**
This bug leads to incorrect assessments.

**Steps To Reproduce**

1. User/Role: idir/analyst
- Access a MY Report submitted to government
- Add a comment and save
- Return the report to the supplier
2. User/Role: bceid/Signing Authority
- Make a change to the LDV Sales figure
- Resubmit the report
3. User/Role: idir/analyst
- Open the resubmitted report
- Observe that the Assessment tab displays incorrect starting balance information

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1888?planning-poker) with Zenhub @JulianForeman
