### ISSUE TITLE
ZEVA - MY Report analyst edit assessment feature

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1894]
**Title:** MY Report analyst edit assessment feature

**Description:** As an analyst making an edit to an assessment of a Small Vehicle supplier before recommending: I used the Edit feature to add a Make to the Supplier Info. But the edit page imposes a compliance obligation. The Edit page also needs to be updated to recognise a small supplier does not have an obligation. 

**Wireframe:** 
![small-supplier-error.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/c6c41020-f576-4bc1-9215-f29accf73ad7)

**Purpose and benefit to user:**

**Acceptance Criteria:**

- [ ] Given I am a idir analyst, When I am editing an assessment of a small supplier MY report, then I can save the change without a compliance obligation being imposed onto the supplier.

**Development Checklist:**
- [ ] Zero out compliance obligation reduction values when editing a small supplier's assessment

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1894?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745

**Comment by jdon-zev** [comment]
In testing with Shaylene we are still seeing an issue on the edit screen - see attached screenshot. When the analyst changes the sales figure it does show a new/edited credit obligation when this should be zero.

**Comment by shayjeff** [comment]
[Uploading... screenshot.docx]
