### ISSUE TITLE
ZEVA - MY Report assessment reduction (Small supplier)

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1898]
**Title:** ZEVA - MY Report assessment reduction, small supplier

**Description:**
The assessment tab on the IDIR side should not impose a reduction or alter the closing balance of a small supplier. 

**Wireframe:** <link>
![sm-red-error.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/2acddc88-87b0-48a3-b010-e9df90e3757d)

**Purpose and benefit to user:** A small supplier should not have any credit reduction, their assessed balance should not be reduced.

**Acceptance Criteria:**

- [ ] Given I am a idir\analyst, When I am recommending a small supplier assessment to the director, then there should be no credit reduction made against the suppliers credit balance.

**Development Checklist:**
- [ ] Edit logic around credit reduction to not ensure there is no reduction happening at the end of the reporting process.
- [ ] Modify front-end of assessment tab to match what credit reduction looks like in the compliance obligation tab for small suppliers

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1898?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745
