### ISSUE TITLE
ZEVA - Reassessment History bug

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1900]
**Describe the Bug**
During the reassessment process, if the director clicks Save to save a comment, the directors name replaces the analyst name in the Recommend portion of the history.

![history-bug.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/8d75c69f-dc9e-4ade-bc29-88a7b8f1ac31)

**Expected Behaviour**
The history information should never change in this way, history records need to be permanent.

**Actual Behaviour**
The directors name will replace the analysts name if they click save.

**Implications**
The history information will be incorrect.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir/director
1. Go to a Reassessment in recommended status, see analyst name in history as recommending the reassessment
2. Add a comment and click Save, see the history change to show my name as director instead of the analysts name

**Comment by JulianForeman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1900?planning-poker) with Zenhub @tim738745
