### ISSUE TITLE
ZEVA - MY Report history bug

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1901]
**Describe the Bug**
IDIR user name is being displayed on BCeID side on returned report line.

**Expected Behaviour**
Government user names are only displayed internally and should not be displayed to external users, it should display as 'Government of B.C.'

**Actual Behaviour**
IDIR user name is being displayed on BCeID side on returned report line.

![idir-user-name-bug.png](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/99782f25-496a-4ec0-af41-4b5c541f3a41)

**Implications**
Government user names should not be displayed to external users,

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: bceid/ZEVA user
1. Go to a MY Report that has been returned by government
2. See government user name in history

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1901?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745
