### ISSUE TITLE
ZEVA - MY Report, Reassessment and Supplementary Report history workflow review

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1902]
**Describe the Bug**
History information is complete in the final stages of these records but are missing information at various stages throughout the process. Review the code to ensure the latest transactions are being displayed throughout the workflow.

**Expected Behaviour**
The history information should be added to each step of the way.

**Actual Behaviour**
There are stages that have been demonstrated where the most recent transaction is missing but are displayed at the final stage.

**Implications**
History information is important throughout the process, not just at the end.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir\analyst
1. Work through these processes watching the history component.

**Notes:**
Could just involve deriving the history from the sequence of recorded statuses (frontend - ComplianceHistory.js). If this is not sufficient to capture everything, we may need to consider adding more statuses and all the work that surrounds that (e.g. user does something, and that creates a record with that new status; this is backend stuff and will be more work).

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1902?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745

**Comment by airinggov** [comment]
There are still bugs with final version of the history, work from card ### is going to be continued within the scope of this card. Whoever takes this card may want to meet for a testing session to see where some of these bugs still exist.
