### ISSUE TITLE
ZEVA - Investigate how to retain historical record of information on ZEVA and count of errors for ICBC

### ISSUE THREAD

**Issue by kcabhar** [bcgov/zeva#1906]
**Problem Description** 
**In order to** have ZEVA as an accurate reporting system, it **needs to** be able to retain a historical record of information submitted from suppliers to government and information issued from government to suppliers. James to provide a list of pages and screen shots of records that need to be retained.

**Solution Needs - What to Investigate:**
- Investigate the list provided by James - what will it take to retain historical record and what would be the best approach to ensure records are kept for all pages. 
- Count of errors for ICBC (is this related to retaining information or a logic issue?)

**Timebox**
1 or 2 days of work - 5 estimation. Spend more time on the first bullet (prioritize over ICBC count).

**Outcome**
Details describing the outcome of the research 
- Was it successful? What direction should the work go? 
- Was it unsuccessful? Discuss next steps with team

**Additional Context**
- enter text here
- enter text here

**Comment by airinggov** [comment]
"James to provide a list of pages and screen shots of records that need to be retained." hasn't been created yet. Al to set up meeting with Tim to discuss best method and format to provide this list (set for Aug 30). Al will the create list and potentially create cards for individual application components to be worked on in later sprints.

**Comment by airinggov** [comment]
Al to create cards for each component that need data to be permanently stored.
