### ISSUE TITLE
ZEVA - MY Report Assessment credit reduction header

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1912]
**Describe the Bug**
MY Report Assessment (and Compliance Obligation tab) credit reduction header is doubled up on Large supplier page but missing from medium supplier.

**Expected Behaviour**
Large supplier should see the "Unspecified ZEV Class Credit Reduction" header
Medium supplier should see the "Compliance Ratio Credit Reduction" header

large supplier
![lg-sup-a.PNG](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/54936d56-56b3-4259-901e-7d4088bc2fe0)

medium supplier
![med-sup-a.PNG](https://images.zenhubusercontent.com/63b7471574cb4a2d5b484c9f/d1d57980-8459-4653-909a-e4fd2c50ec5c)

**Actual Behaviour**
MY Report Assessment  (and Compliance Obligation tab) credit reduction header is doubled up on Large supplier page but missing from medium supplier.

**Implications**
confusing for both suppliers, conflicting info for large, missing info for medium

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: both idir and bceid zeva users
1. Go to an assessed MY report
2. See Assessment tab and Compliance Obligation tab

**Notes:**
Probably just a frontend display issue; check the conditional rendering based on the supplier's size.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1912?planning-poker) with Zenhub @AlexZorkin @JulianForeman @tim738745
