### ISSUE TITLE
ZEVA - Supplier credit balance in header

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1928]
**Title:** Rebuild the credit balance indicator on the supplier header.

**Description:** The balance indicator was removed as part of the credit transaction page redesign. This card is to rebuild that feature.

**Wireframe:** 
balance
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/163585536?mode=fm

deficit
https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/163586079?mode=fm

**Purpose and benefit to user:** This provides the supplier their current balance from anywhere in the application.

**Acceptance Criteria:**

- [ ] Given I am a BCeID Zeva user, When I am logged into ZEVA, then I see my credit balance in the top right of the header
- [ ] Given I am a BCeID Zeva user, When I am logged into ZEVA, then I see the word 'Deficit' in the top right of the header if I had a credit deficit in my last MY Report assessment

**Development Checklist:**
- [ ] There may need to be some refactoring involved to avoid duplicating code; performance may also be an issue that should be looked at.

**Notes:**

**Comment by tim738745** [comment]
PR build link: https://zeva-dev-1934.apps.silver.devops.gov.bc.ca/

**Comment by airinggov** [comment]
Looks great, we should wait for James to review now before moving this any further.
