### ISSUE TITLE
ZEVA - Bug - Credit Agreements page idir

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1938]
**Describe the Bug**
The status box is displaying the current login idir user name and not saving the transaction user Fname Lname.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVpWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--01023dfb3ea1195f7660f2c7eafbbfa376599808/credit-agreements-bugs.png)

**Expected Behaviour**
The status box should record and display the user first and last name along with the date/time stamp as per normal.

Note gov user names only display on the IDIR side, not on the BCeID side. 

**Actual Behaviour**
Status shows the user name of whoever is currently logged in.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: idir\analyst
1. Go to Credit Agreement page
2. Click on New Transaction button
3. Fill in details and Save transaction
4. See user name in status

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1938?planning-poker) with Zenhub @tim738745
