### ISSUE TITLE
ZEVA - Bug - Missing Comma

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1939]
**Describe the Bug**
The LDV sales number displayed on both the Compliance Obligation and Assessment tabs is missing the comma.

**Expected Behaviour**
The LDV Sales number should have a comma as consistent throughout the site.

**Actual Behaviour**
The number is missing the comma

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXBWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d54f309e7255d25d78849f16a213f12fa5bb9f0/missing-comma.png)

**Implications**
A clear and concise description of any implications.

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1939?planning-poker) with Zenhub @tim738745

**Comment by jdon-zev** [comment]
ON dev all of these figures are still shown without the comma.

**Comment by shayjeff** [comment]
Comma is still not appearing on the compliance obligation tab when in certain statuses.  It appears when it has been assessed but doesn't in other statuses.

**Comment by JulianForeman** [comment]
Can you attach a screenshot of where you are still seeing the missing comma?

**Comment by shayjeff** [comment]
[Uploading... image.png]

**Comment by JulianForeman** [comment]
I can't see that image, could you try re-uploading it?

**Comment by JulianForeman** [comment]
This issue should be resolved now but please test the same field while it's disabled and while it's editable because I had to update how we handle the input box specifically to accommodate a formatted string or a number respectively.
