### ISSUE TITLE
ZEVA - MY Report Print page update

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1941]
**Title:** MY Report Print page update

**Description:** Remove the Create Supplementary Report / Print Page button bar from displaying/printing in the print page format

**Wireframe:** 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjViIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f5d8b731c840f76d7e9ee624e0cfdc86079d0d9f/print-page.png)

**Purpose and benefit to user:**
This will save paper, therefore it will save trees, therefore it will save the environment, therefore the user will be able to live on the Earth longer.

**Acceptance Criteria:**
- [x] Given I am a user, when I am on the MY Report Print page, then the "Create Supplementary Report / Print Page" button bar should not be visible or printed.
- [x] Given I am a developer, when I review the print page format, then the button bar removal should align with the wireframe provided.

**Development Checklist:**
- [x] Ensure that the removal of the button bar does not affect the layout or formatting of the remaining content.
- [x] Test the updated print page on multiple devices and browsers to ensure consistent display.
- [ ] Update any user documentation or help guides to reflect the changes in the print page format.

**Notes:**
- While the button bar is essential for the digital format of the report, it is superfluous in the printed version. Care should be taken not to remove it from the digital version.
- Feedback from users indicated a preference for a cleaner print page layout, which sparked this ticket.

**Comment by AlexZorkin** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1941?planning-poker) with Zenhub @tim738745
