### ISSUE TITLE
ZEVA - Credit transactions pages idir, Edit comments

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1942]
**Title:** The comment feature between the analyst/director does not have the edit function.

**Description:**
The Edit function should be available to both the Analyst and Director to edit their own comments only as available on MY Reports on the following pages:

- Credit Transfer
- Initiative Agreement
- Purchase Agreement
- Administrative Credit Allocation
- Administrative Credit Reduction
- Automatic Administrative Penalty

**Wireframe:** <link>
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVpWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--01023dfb3ea1195f7660f2c7eafbbfa376599808/credit-agreements-bugs.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWRWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--785887ac3f4c5d16c5c38546fd3ddec735118141/credit-agreements-bugs-2.png)

**Purpose and benefit to user:** Users can correct problems with their comments. The expectation to edit comments has been set by the MY Report commenting feature.

**Acceptance Criteria:**

- [ ] Given I am a idir\analyst or director, When I am processing a credit transaction of any type, then when I add a comment I can edit that comment up until the transaction is in its final state when it will no longer be editable

**Development Checklist:**
- [ ] Check if the same comment component as model year report is being used on other pages as well.
- [ ] Assuming they are the same then add the edit feature onto those pages.
- [ ] Otherwise update those components to include an edit feature.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1942?planning-poker) with Zenhub @tim738745 @JulianForeman
