### ISSUE TITLE
ZEVA - Slow loading of credit applications

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1959]
**Title:** Slow loading of credit applications

**Description:** Credit applications, especially ones larger than 1,000 VIN are very slow to load, both initially and when opening previously validated and saved applications. Often resulting in the We're Sorry error.

**Wireframe:** <link>
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXExIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0beba876246384ad35df673fa83a44a85fd8ef7f/Capture.PNG)

**Purpose and benefit to user:**
Leading up to compliance deadline it is critical that government can process applications efficiently before Sept 30.

**Acceptance Criteria:**

- [ ] Given I am a IDIR\analyst, When I am processing credit applications, then I can load and navigate the pages of the application efficiently and without error.

**Development Checklist:**
- [ ] Deriving the warnings is taking a very long time - see if we can optimize this.

**Notes:**

**Comment by airinggov** [comment]
@tim738745 I don't know if this is an existing issue or a new issue but it doesn't appear 'Error 31 Duplicate VIN' is being flagged if it is flagged as '11 Not registered in BC'

**Comment by tim738745** [comment]
@airinggov which credit application (id#)?

**Comment by airinggov** [comment]
@tim738745 480 in dev

**Comment by airinggov** [comment]
@tim738745 would it be easy to swap the button sequence so the Apply button is next to the drop down and Clear Filters is on the right of both?

**Comment by tim738745** [comment]
@airinggov in the case of duplicates, should we flag all of them? That is, if we have 2 vins that are duplicates of each other, do both of them get associated with a warning 31 or only one of them?

**Comment by airinggov** [comment]
@tim738745 31 errors are flagged on all duplicates with no checkbox for any of them, so there is no way to issue even one of the duplicates. They get sent back to the supplier for them to figure it out.

**Comment by airinggov** [comment]
@tim738745 it is working this way in production presently, Shaylene was just showing me

**Comment by tim738745** [comment]
@airinggov I fixed the duplicate warnings stuff; there's a PR up for it right now; will let you know once it's on dev

**Comment by airinggov** [comment]
@tim738745 great, thanks Tim
