### ISSUE TITLE
ZEVA - Credit Application Submitted Date

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1964]
**Title:** Credit Application Submitted Date 

**Description:**The submission date of a credit application is being lost after it is Validated and Recommended. Retain the submission information in the History line in the alert as it is after it is issued.

**Wireframe:** <link>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1hsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a3e939f6ee62a98388397e4722b0f569111d8ec4/ca-4.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczNrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40a092f035c0ae7d946e7e50fde8071d0f9106e1/ca-2.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3JsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1bfd49bdf5d731663007464793542782c79ed174/ca-3.png)

**Purpose and benefit to user:** Government users would like to know the submission date of the application as a permanent piece of information.

**Acceptance Criteria:**

- [ ] Given I am an idir analyst, When I Validate and Recommend a credit transfer, then the submission info gets added to the History line as it does when it is Issued.

**Development Checklist:**
- [ ] Retrieve and display the submission date of a credit application when the application has a status of Validated or Recommended.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1964?planning-poker) with Zenhub @JulianForeman @tim738745
