### ISSUE TITLE
ZEVA - Force ZEV makes to be all cap

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#1994]
**Title:** Force ZEV makes to be all cap regardless how they are typed in.

**Description:** ZEV makes should always be all caps to be consistent throughout the site and to simplify error 41 checking in credit applications.

**Wireframe:** <link>

**Purpose and benefit to user:** Makes will be consistent and won't throw unexpected 41 errors for simple case issues.

Makes can be entered in a couple areas, the main place being the New ZEV Model form the suppliers enter. Additional makes can be entered in the MY Report by both suppliers and IDIR analysts. The form appears to force all caps but it must not be that way in the database.

**Acceptance Criteria:**

- [ ] Given I am a BCeID ZEVA User, When I am entering a new ZEV model, then when I type the vehicle Make it is forced to be all caps.
- [x] Given I am a IDIR Analyst, When I am processing a credit application, then 41 errors won't appear for simple case issues.

**Development Checklist:**
- [ ] Add function to the string when it is entered to force all letters to capitals
- [x] Add check on backend to force capitals when comparing strings so that error isn't raised

**Notes:**

**Comment by JulianForeman** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/1994?planning-poker) with Zenhub @tim738745

**Comment by tim738745** [comment]
Note: only the error 41 fix was done; users may still enter their vehicle makes in whatever case they choose.
