### ISSUE TITLE
ZEVA - Error 71 BCeID Excel error download

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#2015]
**Title:** Error 71 BCeID Excel error download

**Description:** Credit Applications: When error 71 are returned to the supplier/not issued credits, the Excel download should specify the new error. This is the text to be included in the error download: "Wrong model year to be issued with compliance report"

**Wireframe:** <link>

**Purpose and benefit to user:**
I can download the error VIN in the Excel file so I can resubmit them at a later date.

**Acceptance Criteria:**

Given I am a BCeID ZEVA User, when I am looking at a CA that was issued with 71 Errors, then I can download those in the Excel file so I can resubmit them at a later date.

**Development Checklist:**
- [ ] Ensure when downloading supplier error excel spreadsheet it uses the stored warnings, which, in some cases, would include the the new error code.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2015?planning-poker) with Zenhub @JulianForeman @tim738745
