### ISSUE TITLE
CTHUB (ZEVA) - VIN Decoder Investigation

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2024]
**Problem Description** 
In order for CTHUB to have the capability to VIN decode makes and models for business users and if possible, to go down to the trim level, similar to what Stats Canada has done.  Jenna (CTUB lead) sent over coding documents for different VIN decoders that can possibly be used to start the process. A VIN decoder contract is still being finalized. 

**Solution Needs**
- Investigate the documents and information provided by Jenna.
- Determine if the free VIN decoder and the coding information is enough to start working on the VIN decoder in CTHUB.   

**Timebox**
- 5

**Outcome**
Details describing the outcome of the research 
- Was it successful? What direction should the work go? 
- Was it unsuccessful? Discuss next steps with team

**Additional Context**
Link to documents:
https://bcgov.sharepoint.com/:f:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Vin%20Decoding?csf=1&web=1&e=38ecyI

We'll also need to think about the architecture here; if I remember correctly, multiple entities need access to the decoded vins (metabase, ZEVA, and someone mentioned they want API access as well); perhaps the vin decoder should be a standalone mini-app?

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2024?planning-poker) with Zenhub @JulianForeman @tim738745

**Comment by tim738745** [comment]
I wrote up a document regarding how vin decoding could work; it's in the team zelda chat under files/_CTHUB_/Vin Decoding/vin decoding.docx
