### ISSUE TITLE
ZEVA - amend test_transfer_pass

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2045]
**Describe the task**
Amend the test_transfer_pass test

**Purpose**
The test_transfer_pass() test in test_credit_transfers.py fails intermittently even though the code it's testing has not changed. The failure occurs on line 134; specifically, the failure is 400 != 390. This is probably occurring because the database changes that happen earlier in the test have not yet been committed when line 134 is executed. To address this, we can use the on_commit() function: https://docs.djangoproject.com/en/4.2/topics/db/transactions/#performing-actions-after-commit

**Acceptance Criteria**
- [ ] Use the on_commit() function to execute the last bit of the test.
- [ ] Check that the test passes

**Additional context**

**Comment by shayjeff** [comment]
Tested by Sr Dev Tim.
