### ISSUE TITLE
ZEVA - amend test_list_transfer

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2057]
**Describe the task**
Similar to issue 2045, except it's a different test:
Traceback (most recent call last):
  File "/github/workspace/api/tests/test_credit_transfers.py", line 51, in test_list_transfer
    self.assertEqual(len(result), 2)
AssertionError: 3 != 2

**Purpose**
Similar to issue 2045, except it's a different test

**Acceptance Criteria**
Similar to issue 2045, except it's a different test

**Comment by shayjeff** [comment]
Tested by Sr. Dev Tim.
