### ISSUE TITLE
ZEVA - MY Report History wording refinement

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#2061]
**Title:** MY Report History wording refinement

**Description:** The lines regarding report being returned by the director or analyst need to be better written so as not to be confused.

**Wireframe:** <link>
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--174b43e00b296fef7a600ddb5142f2de0b6c5684/image.png)

**Purpose and benefit to user:**
More clarity with the wording, change text to read:

Model year report returned to the supplier [date] by [name]
Model year report returned to the analyst [date] by [name]

**Acceptance Criteria:**

- [x] Given I am a IDIR user, When I am looking at the MY report history, then I am able to easily distinguish between the two different 'returned' actions.

**Development Checklist:**
- [x] In ComplianceHistory.js, we can make changes to the logic so that a more detailed "returned" text is displayed.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2061?planning-poker) with Zenhub @emi-hi @tim738745
