### ISSUE TITLE
ZEVA - Credit application error download 

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#2084]
**Description:** The Excel error download provided to the supplier needs to be changed to include any VIN not issued credits. Presently it only includes error that were first identified when the application is run against ICBC data. It should include any VIN the analyst unchecked and should not include VIN the analyst checked manually.

**Wireframe:** <link>

**Purpose and benefit to user:** The purpose of the download is to communicate with the supplier the error reason that the VIN was not issued credits so that they may submit certain VIN again dependent on the error.

**Acceptance Criteria:**

- [ ] Given I am a BCeID ZEVA user, When I am reviewing an issued credit application with error VIN, then I can download an Excel file containing all VIN that were not issued credits and see the reason for that

**Development Checklist:**
- [ ] Use the record_of_sale and sales_submission_content tables to determine the VINs that were not issued credits, and attach any saved warnings and reasons to the missing vins.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2084?planning-poker) with Zenhub @tim738745 @JulianForeman @emi-hi

**Comment by JulianForeman** [comment]
Is it possible to get a specific report we see this happening on so I can pull the data in locally and see what's going on?

**Comment by airinggov** [comment]
see CA 480 Ford on test
