### ISSUE TITLE
ZEVA - Ability to Upload Model documentation

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2085]
**Title:** Upload supporting documents to verify models.

**Description:** Upload documents to ZEV Models when the supplier send additional information via email to the IDIR users.  This feature will only be available on the IDIR side and documents will only be visible on the IDIR side.  The IDIR analyst have been receiving supporting documents via email to confirm the range information.   

**Wireframe:** <link>

**Purpose and benefit to user:** This will allow the information to be stored in one place (models page) and allow the information to be easily accessible when clicking into the model or looking for the supporting documentation. 

**Acceptance Criteria:**

- [ ] Given I am a <IDIR user>, When I am processing models I have the option of uploading supporting documents (excel or word) , then after the model is validated I can see supporting documents on the same page as the model information page. 

**Development Checklist:**
- [ ] Add frontend component for uploading documents on vehicle models.
- [ ] Modify database model functionality to be able to store uploaded files and associate them to each vehicle model.
- [ ] Modify backend to get uploaded files if they exist.
- [ ] Modify frontend component to display documents and make them downloadable.

**Notes:**
This is to the IDIR users being able to upload documents in credit applications. The only difference is that the information will only be visible on the IDIR side.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2085?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
