### ISSUE TITLE
ZEVA -  Filter for Active Supplier User Email Addresses

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2090]
**Title:** Create a Filter for Active Supplier User Email Addresses

**Description:** 
The active BCeID user email addresses list is in one cell and has no function to sort the emails.  The analyst would like the ability to filter email addresses for one supplier or a few select supplier users and be able to copy the emails. 

The current list is found in the email address section on the vehicles suppliers page.  

**Purpose and benefit to user:**
The analyst emails suppliers when credit application and model year reports have not been submitted.  This will allow them to filter for the supplier emails right in the system and eliminating the step of copying all the emails to excel or word and deleting the ones then don’t need.  

**Acceptance Criteria:**
The ability to filter for one supplier or multiple supplier’s user emails.  

- [ ] Given I am an analyst, When I am searching for user emails, then I would like to filter for emails for a specific supplier and also for multiple suppliers and be able to copy all the emails. 

**Development Checklist:**
- [ ] If not doing an excel download: Create an input box and filter button where the user can enter the supplier names and, upon filter button press, only emails associated with those suppliers are displayed
- [ ] If doing an excel download: Create a new download button, and a new endpoint that serves up the email addresses in an excel file, and call this new endpoint when the button is pressed.

**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2090?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
