### ISSUE TITLE
ZEVA - BCeID Submitted Credit Application Filtering Issue

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2091]
**Describe the Bug**
Suppliers submit credit applications (on the BCeID side). These credit applications then sit in their Credit Applications dashboard folder - awaiting validation. When the analyst on the IDIR side, validate the credit applications, it changes the status from “Submitted” to “Validated” on the IDIR side.  The supplier is no longer able to view these credit application when they try to view them from their dashboard. The only way to view them is to delete the submitted status in the filter bar. Then all credit applications will show. 

When the credit application is issued, the credit application will then show up in the suppliers issued dashboard folder. But there is a period of time where the supplier cannot see all their submitted credit applications given the current filtered view, unless they delete the status "submitted".  

**Expected Behaviour**
When the BCeID user selects "Credit Applications - # awaiting validation" the number of submitted application should appear on that page. 

**Actual Behaviour**
When a BCeID user selects "Credit Applications - # awaiting validation" no submitted applications appear, unless you delete the filter status. 

**Implications**
The BCeID user thinks that their credit applications have disappear and they email the analyst to see what has happened to them.  

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user on dev 
1. Go to dev and use DPAC 
2. Click on Credit Applications - 3 awaiting validation' 
3. See error

Notes:
This was reported by a supplier in an email, but they didn't include screenshots. I have an image to upload, but it's not working for some reason.  

**Development Checklist:**

- [ ] A  figure out what is happening with the filter, is there a different term that can be used on the idir side to filter this data?

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2091?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
