### ISSUE TITLE
ZEVA - Add toggle to upload range information

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#2093]
**Title:** Add toggle/checkbox to upload range information

**Description:** The New ZEV Model page has a checkbox that turns on a file upload utility for the US06 information. This card is to duplicate this for uploading Range information.

Add a new checkbox and text to turn on the upload utility for range information.

**Wireframe:** https://preview.uxpin.com/4946124c44da522837a3b54ccb7b5243fa384039#/pages/165077768

**Purpose and benefit to user:** This will allow suppliers to upload range information when they submit a ZEV model instaed of emailing information.

**Acceptance Criteria:**

- [ ] Given I am a BCeID ZEVA user, When I am submitting a new ZEV model>, then I can upload range information

**Development Checklist:**
- [ ] Make the frontend change (checkbox + text) and make it so that upon checking the checkbox, the upload utility appears
**Notes:**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2093?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
