### ISSUE TITLE
ZEVA- Enhance ZEV System Email Notifications for IDIR Users

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2112]
**Describe the task**
When an action is performed in the Zero-Emission Vehicle (ZEV) System, a generic email notification is sent to IDIR users (Analyst, Manager, or Director) without specifying the details of the action taken, such as comments added, recommended to the director, issued credits, model year assessments, etc. The task is to enhance the email notification system to include specific information about the credit application, model year report, or ZEV model that has been actioned or updated.

**Purpose**
The purpose of this task is to provide IDIR users with more detailed and specific information in the email notifications generated by the ZEV System. By specifying the nature of the action taken on credit applications, model year reports, or ZEV models, it will enable users to quickly understand and respond to the updates without having to manually investigate within the system. This enhancement aims to save time for IDIR users and improve the efficiency of their workflow.

**Acceptance Criteria**
- [ ] Email notifications now includes a link to the credit application, model year report, or ZEV model that has been actioned or updated.
- [ ] IDIR users can easily identify the updated item from the email notification without the need for further investigation.
- [ ] The enhancement does not compromise the security or confidentiality of sensitive information.

**Examples**
- Previous Email:
- A (credit application, model year report or ZEV Model) update has occurred within the Zero-Emission Vehicle Reporting System that may require your action or be of interest to you, please logon to the system at: https://zeroemissionvehicles.gov.bc.ca/
- Updated Email:
- A (credit application, model year report or ZEV Model) update has occurred within the Zero-Emission Vehicle Reporting System. Please log on to the system at: https://zeroemissionvehicles.gov.bc.ca/ then open the following direct link:
(provide full url to open the specific page)

**Development Checklist**
(1) In send_email.py, there should be a function for each type of email (MYR, credit application, etc). Each of these functions is passed the relevant object, so using that, we should be able to construct a valid URL containing the id of the object.

**Additional context**
- We can consider updating the ZEV System dashboard to flag or highlight recently actioned credit applications, model year reports, or ZEV models for quick reference by IDIR users.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2112?planning-poker) with Zenhub @tim738745 @emi-hi @JulianForeman
