### ISSUE TITLE
ZEVA - Implement Loading Icon for "Save" and "Recommended" Actions in MYR

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2113]
**Describe the task**
When an analyst is reviewing a Model Year Report (MYR) in the ZEV Reporting system and clicks on either the "Save" or "Recommend" button, the page should display a loading icon until the save (or recommend) action is completed. This will prevent the analyst from clicking the same button or the other button in quick succession, thereby avoiding the creation of further incorrect data.

**Purpose**
The purpose of this task is to implementing a loading icon during the save or recommend action. preventing rapid triggering of multiple actions and reducing the risk of generating incorrect data entries. 

**Acceptance Criteria**
- [ ] When an analyst clicks on the "Save" or Recommended button, a loading icon should be displayed until the action is completed.
- [x] During the loading period, the buttons (both "Save" and "Recommend") should be disabled to prevent further clicks.

**Development Checklist**
(1) Make it so that when an analyst clicks "save" or "recommend", set the loading state to "true", and set it back to "false" after the request to the backend completes.
  
**Additional context**

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2113?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
Tested
