### ISSUE TITLE
ZEVA - Display timestamps in Pacific Time

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2125]
**Title**
Display timestamps in Pacific Time

**Description:**
Display timestamps in Pacific Time

**Wireframe:** <link>

**Purpose and benefit to user:**

**Acceptance Criteria:**

- [ ] Given I am a user, When I am viewing a timestamp, then it's in Pacific Time

**Development Checklist:**
- [ ] Use setDefault() of moment.js to set the default timezone (https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/)

**Notes:**

**Comment by shayjeff** [comment]
Testing completed: Collaborated with the Sr. Developer as this was challenging to replicate. The Sr. Dev modified the code so I could observe both the incorrect timestamp and the updated timestamp during testing.
