### ISSUE TITLE
CTHUB - call to sockjs url

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2143]
**Describe the task**
Currently, in dev and test, the frontend attempts to call localhost/sockjs-node/info but this endpoint is not configured; we should either not call it or have it call the sockjs route configured in frontend-dc.yaml

**Purpose**
Cleanup

**Acceptance Criteria**
- [ ] Look into not calling the endpoint or calling the right one, decide on best course of action, then implement best course of action.

**Additional context**
- I think it's webpack that's making these calls; perhaps have a look at webpack.config.js in the react project

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2143?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by tim738745** [comment]
This should be resolved now that we're using create-react-app (which supplies its own webpack config).
