### ISSUE TITLE
ZEVA BUG compliance calculator credit balance

### ISSUE THREAD

**Issue by airinggov** [bcgov/zeva#2145]
**Describe the Bug**
Credit balance is being displayed with more than 2 decimal places

<img width="781" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3dzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86189e2e1763f0d7bf31174d69e43c78e9b16e49/decimal.png" alt="decimal.png" />

**Expected Behaviour**
Credits should only ever be shown to 2 decimal places.
(I though we changed that credits were only being stored as 2 decimal places so this could never happen.)

**Actual Behaviour**
The calculator page is showing credits with multiple decimals

**Implications**
I think this is where we start having inconsistencies with rounding.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: bceid
1. Go to dev calculator page 

**Dev Checklist**

- [ ] Check to see if values with more than 2 decimal places are stored in the database
- [ ] If they are then update the models to not accept more than 2 decimal places
- [ ] Check to see if values in the database match what is being displayed
- [ ] Update frontend/backend logic to display the correct values

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2145?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
