### ISSUE TITLE
ZEVA - Bug Issue Affecting Medium Suppliers' Model Year Reports

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2146]
**Describe the Bug**
Discrepancies in the system affecting all medium suppliers across various Model Year reports (2020, 2021, 2022).

**Expected Behaviour**
The assessment page should accurately reflect the credit transactions page for all submitted Model Year reports from suppliers.

**Actual Behaviour**
The ZEVA system incorrectly calculates debits for medium suppliers, resulting in discrepancies across all Model Year reports (2020, 2021, 2022). The system erroneously treated medium suppliers as large suppliers deducting only the unspecified amount instead of the total debit amount (including A credits). Although the values changed in the Model Year reports, the transaction page accurately displays the suppliers' credits.

**Implications**
These inaccuracies affect all medium suppliers and their Model Year reports, potentially leading to confusion and improper compliance assessments across multiple years.

**Steps To Reproduce**
User/Role:
1. Access the ZEVA system.
2. Navigate to any submitted Model Year report from a medium supplier.
3. Compare the assessment page with the credit transactions page.
4. See the discrepancy in the number of debits and the resulting balance.

Development checklist:
(1) Fix the calculation function that's being used to calculate compliance ratio reductions associated with the unspecified ZEV class.

**Comment by airinggov** [comment]
Is the assessment info always calculated? We might consider making the assessment info a snapshot upon the director's assessment.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2146?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745
