### ISSUE TITLE
ZEVA BUG: Error When Attempting to Resubmit Deleted Rejected ZEV Models

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2161]
**Describe the Bug**
When attempting to submit information for a ZEV Model with the same name that has been previously deleted, users encounter an error message stating: "The fields make, model name, vehicle zev type, model year must make a unique set."

**Expected Behaviour**
Users should be able to submit information for a ZEV Model with the same name after it has been deleted without encountering an error message.

**Actual Behaviour**
Upon attempting to submit information for a previously deleted ZEV Model with the same name, users receive an error message preventing submission of the model.

**Implications**
The error message restricts the ability to resubmit information for ZEV Models that were with identical names which stops the user from submitting models for credits. 

**Steps To Reproduce**
**User/Role: BCeID User**
1. Login to the ZEVA System.
2. Submit a ZEV Model with a specific name to Government – it will be rejected by Government.
3. Delete the rejected ZEV Model.
4. Attempt to submit another ZEV Model with the same name.
5. See the error message stating that the fields make, model name, vehicle ZEV type, and model year must make a unique set.

**Notes**
The issue is with the uniqueness constraint on the vehicle model; it needs to be changed to take into account the status of the vehicle; more specifically, it needs to be such that if a vehicle has a status of "deleted", then the uniqueness constraint does not apply; please see https://docs.djangoproject.com/en/3.2/ref/models/constraints/#condition

Screenshot from the test site: 
<img width="861" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--355b7ce6fcf67233f18d967618730edb2fb89784/image.png" alt="image.png" />

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2161?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
Tested - able to resubmit without an error.
