### ISSUE TITLE
ZEVA - 2024 Validated Models Not Appearing in Credit Application Template

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2163]
**Describe the Bug**
When suppliers attempt to download validated 2024 models in their CA template, the vehicles are not populating in the spreadsheet.

**Expected Behaviour**
Upon generating the Credit Application (CA) with the validated 2024 models, the spreadsheet should populate with the respective vehicles.

**Actual Behaviour**
After generating the CA, the vehicles are not populating in the spreadsheet as expected. 

**Implications**
This bug affects the ability to submit credit application because the models are not populating. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Log in with BCEID. 
2. Navigate to the credit application page.
3. Click on the "New Credit Application" tab.
4. Download the sales template with validated 2024 models.
5. Notice that the vehicles do not populate in the spreadsheet.

Note: 
This is affecting supplier ID 5 and 17 in production. Please reach out to the PO for the names if needed.

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2163?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by shayjeff** [comment]
Tested on dev - 2024 models now appear.
