### ISSUE TITLE
Task - Transition from ZenHub to GitHub Projects

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2168]
**Describe the task**
Migrate projects from ZenHub to GitHub Projects.

**Purpose**
To transition project tracking and management to GitHub Projects before the subscription with ZenHub ends, ensuring uninterrupted workflow for the team and maintaining project visibility.

**Acceptance Criteria**
- [ ] Export all relevant project data from ZenHub to GitHub Projects, ensuring all tasks, labels, and Epics are accurately transferred.
- [ ] Verify that all team members have access to GitHub projects and can view/edit them as needed.

**Additional context**
- ZenHub subscription is set to expire the end of the year. However, with the ZEVA rebuild we need to transfer before creating those cards. 
- Review as a team so every one is familiar with GitHub projects.
- Get script from Alex. 

PS: This issue depends on #2199

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2168?planning-poker) with Zenhub @emi-hi @tim738745

**Comment by ArawuSamuel1** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2168?planning-poker) with Zenhub @JulianForeman

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/zeva/2168?planning-poker) with Zenhub @emi-hi @tim738745 @JulianForeman

**Comment by ArawuSamuel1** [comment]
Tim would speak with Alex to get the scripts

**Comment by ArawuSamuel1** [comment]
Hi @tim738745 and @shayjeff i think we can close this ticket, what do you both think?

**Comment by tim738745** [comment]
@ArawuSamuel1 If @shayjeff is okay with the zenhub data that was brought over to this new board, then I think we can close this ticket!

**Comment by shayjeff** [comment]
@ArawuSamuel1 and @tim738745 I'm okay with closing these cards, but we need to create a spike card for the closed cards that did not come over from ZenHub. We need to find a way to get that information, whether in a CSV or another format, as it serves as a record of our work. @ArawuSamuel1 can you create that card?

**Comment by ArawuSamuel1** [comment]
Yes, I have created the card - https://github.com/bcgov/zeva/issues/2199

**Comment by ArawuSamuel1** [comment]
We closed this issue because we got directions frtom Suzanne that we can all closed issues from zenhub on github issues.
