### ISSUE TITLE
CTHUB - Make Column Casing Consistent

### ISSUE THREAD

**Issue by JulianForeman** [bcgov/zeva#2176]
**Task Description**
Create a preparation function for the GER upload (potentially all uploads, ask Katia about this) that keeps the title of each column's capitalization consistent.

**Purpose**
It makes it more readable and also allows for us to better check what is inside a cell in the future for duplicates/naming schemes etc...

**Acceptance Criteria**
- [ ] The read/returned columns should all be capitalized the same way

**Development Checklist**
- [ ] Create either a re-usable preparation function for specifically GER or write it into the actual uploader to capitalize column names the same way.

**Additional context**
Please see GER Notes 1.1 located in the GER_Notes file contained in the shared CTHUB folder in Teams.

We can use built in functions to make everything capitals or lowercase or title structure so this shouldn't be much work.

**Comment by shayjeff** [comment]
Replaced with card #312 because this one was opened under ZEVA and not CTHUB.
