### ISSUE TITLE
ZEVA - supplementary report wrong ldv sales value + error upon issuing assessment

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2178]
**Describe the Bug**
On zeva dev, Ford's supplementary report has the wrong previous LDV sales number, and when the director tries to issue the reassessment, an error occurs.

**Expected Behaviour**
The above shouldn't happen

**Actual Behaviour**
The issue described two sections above does happen.

**Implications**
This is not good.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: Director on zeva dev:
1. Go to Ford's supplementary report (MYR id 145, supp id 149)
2. See/recreate errors as described above

**Comment by shayjeff** [comment]
Tested!
