### ISSUE TITLE
CTHUB - GER Typo checker for Applicant Name

### ISSUE THREAD

**Issue by katerinkus** [bcgov/zeva#2180]
**Describe the task**
`Applicant Name` column is inconsistent. For instance, "ABC & Company" could also be spelled "ABC and Co". Understanding which spelling or name is correct is impossible without human judgment.  The person uploading a dataset should get a warning message (before the dataset is finally uploaded). This warning message should contain a list of lists of values that are very similar, indicating that it is possible the same person/entity. From there the user can work on their spreadsheet to fix issues and try uploading again. The user should also have an option to ignore this message and proceed to upload regardless.

**Purpose**
It normalizes the data for easier retrieval and proper groupings.

**Acceptance Criteria**
- [ ] Similar sounding names are displayed to the user in a warning before the final upload
- [ ] User can ignore the warning and proceed to the upload

**Additional context**
- Please see [GER_notes_for Agile_team](https://bcgov.sharepoint.com/:u:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_CTHUB_/Data_2024/GER_SUVI/GER_notes_for_Agile_team.html?csf=1&web=1&e=1xescZ), section 3 for my implementation using python library [difflib](https://docs.python.org/3/library/difflib.html)

**Comment by shayjeff** [comment]
Closing as card was opened under the wrong project.  New card # 328
