### ISSUE TITLE
ZEVA - Administrative Credit Transaction Backdating Issue

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2191]
***Title:**
Administrative Credit Transaction Backdating Issue

**Description:**
We are trying to  backdate an administrative credit transaction (addition or reduction) and it's not showing up correctly. The transaction only appears on the credit transaction page, but it does not adjust the applicable credits and is also not visible on a reassessment or supplementary report report. 

**Purpose and benefit to user:**
To ensure that all administrative credit transactions, including backdated ones, are accurately reflected in the credit transactions, model year reports, and reassessments. This will provide users with correct credit balances and historical records.

**Acceptance Criteria:**
- [ ] Given I am an IDIR user, When I perform an administrative credit transaction, then it adjusts the applicable credits and is visible on the credit transaction page and the model year report.
- [ ] Given I am an IDIR user, When I backdate an administrative credit transaction to a specific compliance period, then it appears in the credit transactions for that period.
- [ ] Given I am an IDIR user, When I perform a reassessment for a specific compliance period, then the backdated transaction is reflected in the reassessment.

**Development Checklist:**
- [ ] Backdated transactions appear in the credit transactions for the specific compliance period.
- [ ] Reflect backdated transactions in reassessments for the specific compliance period.

**Notes:**
Please see PO if more information is needed.

**Comment by shayjeff** [comment]
Closing this card as this function is working as intended.

**Comment by tim738745** [comment]
Hi @shayjeff, please let the business area know that, currently, there are certain limitations around this backdating feature:

(1) Admin. credit reductions and allocations should not be backdated by more than 1 compliance year (e.g. current compliance year is 2023, so they can backdate to compliance year 2022 (I used Sept. 30, 2023), but not 2021 or earlier.

(2) If an admin. credit reduction or allocation backdated to compliance year "Y" has been issued, they must, afterwards (not before), create and assess a reassessment of the Year "Y" model year report.

(3) They must not assess a model year report before all backdated reductions/allocations have been accounted for in assessed reassessments.

Also, could you please double check with them to see if they really want this feature? This was extremely difficult to implement and I don't have the utmost confidence in it. I would strongly suggest just issuing a non-backdated admin. reduction (i.e. one dated Oct.1 2023 or later).

**Comment by shayjeff** [comment]
@tim738745 the C&E team would like to hold off on this card. We will work on card 2195 this sprint, which will open up the fields for the director to modify.
