### ISSUE TITLE
ZEVA - Credit Amount Modification in Reassessment Report

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2195]
**Title:**  
Credit Amount Modification in Reassessment Report

**Description:**  
As a system user, I would like to be able to change the supplier credit amounts when a reassessment report is created. This will allow the flexibility for the user to update credits in case of an error. The capability to update the issue's credit amount should automatically change the balance before reducing and the assessed balance. It is essential to ensure that everything flows correctly in the reassessment and that the balances are accurately reflected.

**Wireframe:**  
If a wire frame is needed, please let me know. 

**Purpose and benefit to user:**  
This feature provides users with the flexibility to correct any errors in credit amounts during the reassessment process. By allowing modifications to credit amounts, IDIR users can ensure that the balances are accurately adjusted. 

**Acceptance Criteria:**
- [ ] Given I am a  IDIR user, When I am creating a reassessment report, then I can modify the credit amounts.
- [ ] Given I am a system user, When I update the credit amounts, then the balance before reduction is automatically adjusted.
- [ ] Given I am a system user, When I complete the reassessment report, then all balances are accurately reflected in the system.

**Development Checklist:**
- [ ] 

**Notes:**
- Conduct thorough testing to verify that the credit modification feature works seamlessly and that all balances are correctly updated.

**Comment by katerinkus** [comment]
This ticket had issues according to the business area team.

**Comment by katerinkus** [comment]
Tested and passed with the real scenario.

**Comment by katerinkus** [comment]
I will make another card to follow up on remaining comments.
