### ISSUE TITLE
Investigate Missing Closed Cards from ZenHub Migration

### ISSUE THREAD

**Issue by ArawuSamuel1** [bcgov/zeva#2199]
**Problem Description** 
Investigate why certain closed cards did not transfer from ZenHub during the migration process. This spike aims to understand the root cause of the issue and determine potential solutions.

**Solution Needs**
- Identify which closed cards are missing from the migration.
- Analyze the characteristics of these missing cards.
- Investigate the migration process and any potential limitations or filters applied.
- Determine if this is a systemic issue or specific to certain types of cards.
- Explore possible solutions or workarounds to retrieve the missing data.

**Timebox**
- TBD?

**Outcome**
Details describing the outcome of the research 
- A comprehensive list of missing closed cards is compiled.
- The root cause of the migration failure for these cards is identified.
- A report detailing findings and potential solutions is prepared.
- Recommendations for next steps are provided, including any necessary follow-up tasks or stories.

**Additional Context**
- This spike may require collaboration with the ZenHub support team or reviewing ZenHub's API documentation.
- The outcomes of this spike may lead to additional user stories or tasks for implementing a solution.
- This issue depends on #2168

**Comment by ArawuSamuel1** [comment]
Shaylene will reach out to susan to figure out next steps

**Comment by shayjeff** [comment]
Suzanne has stated that other teams were able to export their data. She will be reaching out to Tim about this.

**Comment by ArawuSamuel1** [comment]
Great, thank you Shaylene

Best Regards,
Samuel Arawu, PMP, PROSCI, CBAP, PSM, ICP-ACC, SPC 6.0, PSPO, ITIL
Snr. Scrum Master,
Natural Resource Information & Digital Services Division,
Ministry of Land, Water and Resource Stewardship.

**Comment by ArawuSamuel1** [comment]
@tim738745 says that all zenhub cards are automatically on github repos so should we need any card, we can always get it. Closing out this ticket.
