### ISSUE TITLE
ZEVA Update ZEVA System for Class 2b Vehicles, Adjust GVWR Limits

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2203]
**Describe the task**
Update the ZEVA system to capture Class 2b vehicles by including vehicles with a GVWR of 4,536 kg or less, effective October 1, 2024. Update the existing warning system to reflect the new GVWR limit of 4,536 kg, replacing the current limit of 3,856 kg. Implement a flagging system to identify vehicles with a GVWR above 3,856 kg but below 4,536 kg as Class 2b on the weight line in the system. Additionally, update the upload feature's wording to ensure all required documents, including proof of range, can be included, as Class 2b vehicles will not have a posted range. 

**Purpose**
This task is to include the classification of Class 2b vehicles in the ZEVA System, aligning with regulatory changes. The flagging system aids suppliers and IDIR users by identifying vehicles that fall within the specified GVWR range for Class 2b. The warning system will continue to alert suppliers if a vehicle's GVWR exceeds 4,536 kg.

**Mock Up** https://www.figma.com/design/ijCyqDXXGVGDmmyfaXzPhk/ZEVA?node-id=0-1&t=eVcIVCjqxjN1NrQA-1 
**Proto**  https://www.figma.com/proto/ijCyqDXXGVGDmmyfaXzPhk/ZEVA?page-id=0%3A1&node-id=167-218&viewport=-378%2C247%2C0.33&t=nDxjXDPyVg1sHib9-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=167%3A218 

**Acceptance Criteria**
- [x] Update the ZEVA system's GVWR limit from 3,856 kg to 4,536 kg.
- [x] Create a flagging system for vehicles with a GVWR between 3,856 kg and 4,536 kg, marking them as Class 2b on the weight line.
- [x] Update the upload feature to accommodate all required documents, including proof of range for Class 2b vehicles.

**Additional context**
- The current GVWR limit is 3,856 kg and will be updated to 4,536 kg to include Class 2b vehicles.
- This change aligns with regulatory updates effective October 1, 2024.
- The upload feature's wording update is necessary to include proof of range for Class 2b vehicles, which might not have a posted range.

**Comment by ArawuSamuel1** [comment]
This is most likely a new ticket and I will try to create one 

- [ ] Update the information provided in a comment from the Government back to the vehicle suppliers to ensure that the commentator’s name is not displayed

**Comment by tim738745** [comment]
@shayjeff I just wanted to confirm that "2B" is not a new "vehicle class" as defined in the ZEV Act right? We still have exactly one "vehicle class", and that's the "reportable vehicle class"? We're simply expanding our only vehicle class to include both LDV and 2B vehicles? I'm asking because I'm concerned about section 12 of the Act (offsetting credits and debits), which seems to say that a credit may offset a debit only if both the credit and the debit are associated with the same vehicle class. So if we had 2 distinct vehicle classes, then there could be a lot more work we need to do. Thanks!

**Comment by shayjeff** [comment]
@tim738745 that is correct it's not a new class. I just received clarification from the BA and they only want a 2B flag on the idir side and not the BCeId side.

**Comment by katerinkus** [comment]
- [x] Update the ZEVA system's GVWR limit from 3,856 kg to 4,536 kg.
- [ ] Create a flagging system for vehicles with a GVWR between 3,856 kg and 4,536 kg, marking them as Class 2b on the weight line.
- [x] Update the upload feature to accommodate all required documents, including proof of range for Class 2b vehicles.

**Comment by katerinkus** [comment]
- [x] Update the ZEVA system's GVWR limit from 3,856 kg to 4,536 kg.
- [x] Create a flagging system for vehicles with a GVWR between 3,856 kg and 4,536 kg, 
- [ ] marking them as Class 2b on the weight line.

**Comment by katerinkus** [comment]
- [x]  marking them as Class 2b on the weight line.
