### ISSUE TITLE
Prevent commentator's name from displaying when updating information from comment

### ISSUE THREAD

**Issue by ArawuSamuel1** [bcgov/zeva#2206]
**Describe the task**
Update the system to hide the commentator's name when transferring information from a Government comment back to vehicle suppliers. This change aims to enhance confidentiality in the commenting process.

**Purpose**
To maintain a level of anonymity for commentators, particularly when feedback is relayed from the Government to vehicle suppliers.

**Acceptance Criteria**
- [ ] Modify the comment relay system to exclude the commentator's name when sending information to vehicle suppliers
- [ ] Ensure that all other relevant comment information is still accurately transmitted
- [ ] Add a visual indicator or note that the comment is from a Government source without revealing the specific commentator
- [ ] Test the feature with various comment types and user roles to ensure consistent functionality
- [ ] PO should inform the C & E team to update any relevant documentation or user guides to reflect this new privacy feature

**Additional context**
- Review current data flow of comment information
- Identify all points where commentator names are displayed or transmitted
- Ensure that the removal of the name doesn't break any existing functionality

**Comment by ArawuSamuel1** [comment]
Hi @JulianForeman here is the card I created, please go through and see what you'd love to add or change

**Comment by katerinkus** [comment]
Works for sale submissions and vehicle models. I will make another card for the reminder of cases where the commentator's name is visible.
