### ISSUE TITLE
Create Downloadable Excel Template for Supplier ZEV Sales Forecasts

### ISSUE THREAD

**Issue by ArawuSamuel1** [bcgov/zeva#2207]
**Describe the task**
Develop and implement a downloadable Excel template for suppliers to input and submit their Zero Emission Vehicle (ZEV) sales forecasts.

**Purpose**
To standardize the process of collecting ZEV sales forecast data from medium and large suppliers, ensuring consistency and ease of data entry and submission.

**Acceptance Criteria**
- [ ] Create an Excel template with **predefined columns** for all required forecast data such as: Model Year, Make, Model, Type, Range (km), Class, Interior Volume (cu ft.), Total Sales Forecast. 
- [ ] Ensure completeness of entered data
- [ ] Include clear instructions within the template for suppliers on how to fill it out
- [ ] Ensure the template is compatible with the upload feature mentioned in #2204
- [ ] Create a button to download the Excel spreadsheet template 
- [ ] Create database table for ZEV sales forecast. [Forecast table information](https://bcgov.sharepoint.com/:w:/r/teams/00598-TeamZelda/Shared%20Documents/Team%20Zelda/_ZEVA_/ZEVA%20Card%20Documents/Forecast_table_info.docx?d=w7845d359c95e48a28336a2223c7e155b&csf=1&web=1&e=FylTf1)
- [ ] Test the template with sample data to verify it can be successfully uploaded and processed by the ZEVA system

**Additional context**
- This task is dependent on #2204
- The template should align with the manual entry fields and data requirements specified in #2204
- Consider potential future needs for data analysis when designing the template structure

**Comment by ArawuSamuel1** [comment]
Hi @JulianForeman I have created the card, please read through and see if there is anything you'd like to edit or improve. 

Thank you

**Comment by shayjeff** [comment]
I've added the table please let me know if you have any questions.

**Comment by katerinkus** [comment]
@tim738745 The download works and the drop downs are functional. In the instructions it talks about limits but they are not checked by the spreadsheet (i.e., I can put any number of digits in Model Year, more than 250 chars in Make and Model, etc.). I am assuming it is up to those doing submissions to ensure that:

(1)  "Model Year": Must be a 4 digit number.
(2)  "Make": There is a limit of 250   characters.
(3)  "Model": There is a limit of 250   characters.
(5)  "Range": Must be a number with no more   than 2 decimal places.
(8)  "ZEV Supply Forecast": Must be a number

Spreadsheet template does not impose these restrictions.

**Dropdowns**
Vehicle classe and Interior Volume dropdown match [2024 Fuel Consumption Guide](https://natural-resources.canada.ca/sites/nrcan/files/files/pdf/2024%20Fuel%20Consumption%20Guide.pdf).
Type and ZEV Class match [B.C. Zero-Emission Vehicles Act & Regulation Guidance Document (2021)](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/electricity-alternative-energy/transportation/bc_zev_actregulation_guidancedoc_version1_20210621.pdf).

**Comment by tim738745** [comment]
@katerinkus yes, it is largely the user's responsibility to check that the data they're uploading is valid
