### ISSUE TITLE
ZEVA - Upload forecasted ZEV sales spreadsheet

### ISSUE THREAD

**Issue by ArawuSamuel1** [bcgov/zeva#2209]
Describe the task
Allow user to upload forecast spreadsheet 

Purpose
The integration aims to streamline the process of submitting ZEV sales forecasts for compliance with ZEV Regulation (Act S. 18.1 and Reg S. 16.3). The collected data will aid in policy-making and planning to support the adoption of zero-emission vehicles.

Mock up
https://www.figma.com/design/ijCyqDXXGVGDmmyfaXzPhk/ZEVA?node-id=18-202&t=OvSUrBDTY9QNmqjr-1
Proto
https://www.figma.com/proto/ijCyqDXXGVGDmmyfaXzPhk/ZEVA?page-id=50%3A193&node-id=18-202&viewport=153%2C-256%2C0.46&t=GOidMB0EBpgguc1q-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=18%3A202

The mock-up demonstrates the layout, including an upload area for the Excel template, a table for entering and reviewing forecast data, and sections for calculating total sales.

Upload Section:  a drop area to upload the completed file.
Total Sales Calculation: Automatic calculation of total sales for ICE vehicles, ZEVs, and overall vehicle sales for the required years displayed in that section.

Acceptance Criteria
Drop area to upload the file 
Contents of file are inserted into the database

**Comment by shayjeff** [comment]
The mock-up has been updated to remove the word "sales to supplied or vehicles supplier" Also, the the name of the report is now "Forecast Report."  The spreadsheet will need to be updated to reflect these changes. I've noticed the card is still in progress so wasn't sure if another card was needed to capture these changes.  I can create a new card if needed.

**Comment by katerinkus** [comment]
- [x] Drop area to upload the file

No way for met to check this by myself. I will follow up with Emily.
- [ ] Contents of file are inserted into the database
