### ISSUE TITLE
ZEVA: forecast report template column mapping

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2219]
The business area is going to decide what the "forecast report template" spreadsheet column names are going to be. After they do that, they should send us a revised spreadsheet containing those names, and we have to map those names to our internal column names (please see `src/salesforecast/components/RecordsUpload.js`, and implement the `getInternalRecords()` function there; additional notes are available as comments in the body of the aforementioned function).

**Comment by tim738745** [comment]
Here's the spreadsheet with column names the business area wants:

[forecast_report_template_TG_edits.xlsx](https://github.com/user-attachments/files/16681555/forecast_report_template_TG_edits.xlsx)

**Comment by katerinkus** [comment]
@tim738745 @JulianForeman 
If I put in "Blah" instead of "Model Year" I get a 4-digit warning.
If I put in "Blah" unstead of "Make I get 250 characters warning, etc.

**Comment by katerinkus** [comment]
Resolved here: [#2273](https://github.com/bcgov/zeva/issues/2273)
