### ISSUE TITLE
ZEVA: frontend validation of uploaded spreadsheet

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2220]
Please implement the `validateRecords()` function in `src/salesforecast/components/RecordsUpload.js`. Additional notes are available as comments in the body of the aforementioned function.

**Comment by katerinkus** [comment]
- [x] Model year - 4 integers. A nice to have would be limit (i.e. some realistic time range). Right now I can add 1700 and it is fine.
- [x] Make - 250 chars. 
- [x] Model - 250 chars.
- [ ] Type - to test
- [x] Range - 2 decimals.
- [ ] ZEV Class - to test 
- [ ] Vehicle Class and Interior Volume - to test
- [x] ZEV supply forecast - must be a number.

**Comment by katerinkus** [comment]
Resolved here: [#2272](https://github.com/bcgov/zeva/issues/2272)
