### ISSUE TITLE
ZEVA: forecast report styling

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2221]
Please style the `TotalsTable.js` component, as well as style how the `RecordsUpload`, `RecordsTable`, and `TotalsTable` components appear together in `ConsumerSalesDetailsPage` (please see the following mockup: https://www.figma.com/design/ijCyqDXXGVGDmmyfaXzPhk/ZEVA?node-id=50-193)

**Comment by katerinkus** [comment]
@tim738745 
- [x] 1. Ability to download sample forecast report template works.
- [ ] 2. I do not see:  "Your file has been successfully uploaded. Please review the table below before saving."
- [x] 3. Pagination works but  you need to press enter to switch between pages.
- [x] 4. Totals work.
- [x] 5. Save button is gray until two checkboxes are filled.
- [x] 6. When edit is clicked, the user has to do checkboxes again.
- [ ] 7. I see sales not supplied.

**Comment by katerinkus** [comment]
#2 will be addressed by [#2271](https://github.com/bcgov/zeva/issues/2271).
