### ISSUE TITLE
ZEVA - forecast report confirmation checkbox

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2222]
Please implement the confirmation checkbox associated with the forecast report (please see https://www.figma.com/design/ijCyqDXXGVGDmmyfaXzPhk/ZEVA?node-id=50-193). The save button should be disabled until this checkbox and all other checkboxes are checked. After saving, if the user clicks the "Edit" button (top right of page), then all the checkboxes should become unchecked.

**Comment by katerinkus** [comment]
Both situations worked for me.
