### ISSUE TITLE
ZEVA - conditional rendering of "Vehicles Supplied" wording and update "Vehicle Class"

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2223]
This is related to card #2205  - the "Vehicles Supplied" wording should only apply to MYRs associated with the 2024 compliance year or later (earlier MYRs should continue to have the original wording).

**Describe the task**
Remove "vehicle class" visibility for BCeID users (suppliers) while keeping it visible for IDIR users. On the supplier side, flag any vehicle entries with a weight over 4536 kg. Additionally, hide the classification "2B" if the vehicle weight is between 3856 kg and 4537 kg.

**Purpose**
This will eliminate the use of a vehicle class that is currently not referenced in the Act or Regulations and ensure proper handling of vehicle weight information.

**Acceptance Criteria**
- [ ] Vehicle classification is hidden for suppliers but visible to Idir users.
- [ ] Any vehicle entry over 4536 kg is flagged on the supplier side.
- [ ] Classification "2B" is hidden if the vehicle weight is between 3856 kg and 4537 kg.

Additional context
•	This was new information from the BA after card 2203 was completed. Tim asked me to add the detail to this card. If you have any questions please let us know.

**Comment by katerinkus** [comment]
- [x] Vehicle classification is hidden for suppliers but visible to Idir users.
- [ ] Any vehicle entry over 4536 kg is flagged on the supplier side.
- [x] Classification "2B" is hidden if the vehicle weight is between 3856 kg and 4537 kg.
