### ISSUE TITLE
ZEVA - update compliance ratios

### ISSUE THREAD

**Issue by tim738745** [bcgov/zeva#2265]
**Describe the task**
The compliance ratios for compliance years >= 2026 have been updated by the new ZEVA regulations, and there is a frontend page that displays these ratios, so they should be updated to the new values (please see attached: [Compliance_ratio_changes_ZEVA.docx](https://github.com/user-attachments/files/17051028/Compliance_ratio_changes_ZEVA.docx))

**Purpose**
Make the ZEVA app consistent with relevant legislation/regulations.

**Acceptance Criteria**
(1) Frontend correctly reflects the new compliance ratios (The "Compliance Reporting" -> "Compliance Ratios" page)
(2) Pre-2026 MYRs are not affected; more generally, data that relies (directly or indirectly) on the pre-2026 ratios remain unchanged.

**Development Checklist**
(1) Create a data migration that updates the compliance_ratios table with the new data (i.e. update compliance ratios from 2026-2035 inclusive, delete compliance ratios > 2035).

**Notes**
(1) This work should go into the Oct.21 branch (oct_21_2024_stuff_v1)

**Comment by katerinkus** [comment]
Devs did spot checks and more tests are coming out in the next sprint.
