### ISSUE TITLE
ZEVA - Reassessment based on previous reassessment balance

### ISSUE THREAD

**Issue by katerinkus** [bcgov/zeva#2266]
**Describe the task**
Business area needs a feature that would allow them to do a reassessment based on a previous reassessment. This way year 2020 reassessed balance, for instance, would become the starting balance for year 2021.

**Purpose**
This allows for reassessment adjustments to be propagated into subsequent years.

**Acceptance Criteria**
- [ ] As an IDIR user, I want to create a new reassessment report based on previous reassessment values.

**Comment by shayjeff** [comment]
Tested, works well. Thanks @tim738745
