### ISSUE TITLE
ZEVA - remove commentator's name

### ISSUE THREAD

**Issue by katerinkus** [bcgov/zeva#2267]
**Describe the task**
This ticket relates to [#2206](https://github.com/bcgov/zeva/issues/2206). The app should not display commentator's name in the following:

- [x] agreements
- [x] model year report assessments
- [x] supplemental reports
- [x] transfers

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [x] as an bceid user, comments from idir users on the above listed features are displayed with usernames as something like 'government user' 
- [x] as an idir user, comments from all users show the commentator's usernames
- [x] as a bceid user, comments from other bceid users show the commentator's usernames

**Additional context**
-could write a mixin that can be reused throughout the application

**Comment by shayjeff** [comment]
Testing complete.
