### ISSUE TITLE
ZEVA - Remove automatic reduction

### ISSUE THREAD

**Issue by katerinkus** [bcgov/zeva#2284]
**Describe the task**
Automatic administrative reduction is not a necessary feature. It should be removed.

**Purpose**
This feature automatically deducts B credits when suppliers have insufficient credits but it should not. Deductions should only happen after the model year report is done.

**Acceptance Criteria**
- [x] Automatic administrative reduction is removed
- [ ] The organization that had that happen needs to have the entry removed.

**Additional context**
- This is likely a feature that was being tested at the inception of ZEVA that did not later get deleted.

![Image](https://github.com/user-attachments/assets/a7618ef7-1379-4dbc-b3c9-6ee48e18699c)

**Comment by tim738745** [comment]
One more note: automatic reductions should also not happen when a transfer gets issued (please see line 378 in services/credit_transaction.py)
