### ISSUE TITLE
ZEVA - Credit agreement date flag

### ISSUE THREAD

**Issue by katerinkus** [bcgov/zeva#2301]
**Describe the task**
If the credit agreement does not have a date attached to it, the director gets an error when they try to issue credits. The system should prevent policy analyst from creating credit agreements without specifying a date. 

**Purpose**
Date is required.

**Acceptance Criteria**
- [ ] If there is no date, the system should output a date error for the policy analyst.

**Comment by Lalita-Lala** [comment]
A new ticket [2380](https://github.com/bcgov/zeva/issues/2380) has been created based on this

**Comment by shayjeff** [comment]
Closing this ticket as another ticket was created.
