### ISSUE TITLE
ZEVA - Endpoint testing

### ISSUE THREAD

**Issue by katerinkus** [bcgov/zeva#2313]
**Describe the task**
Testing endpoints to ensure error 403 comes up.

**Purpose**
Provides security.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Some tests are already available.

**Comment by ArawuSamuel1** [comment]
Hi @emi-hi please what do you estimate this card to be?

**Comment by shayjeff** [comment]
Reviewed with dev and all looks good.
