### ISSUE TITLE
ZEVA - MYR draft state and supplier size

### ISSUE THREAD

**Issue by katerinkus** [bcgov/zeva#2330]
**Describe the Bug**
When supplier creates a model year report (MYR) and the supplier size changes during the draft MYR state, the new size is not updated on the assessment page.

**Expected Behaviour**
I expect that the new size gets reflected in the MYR.

**Actual Behaviour**
It is reflected on the supplier page but not on the assessment in the draft MYR.

**Implications**
This means that if the supplier size changes (e.g. increases or decreases), the compliance ratio will be incorrect if they already started a MYR.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role:
1. Create a model year report draft as a supplier.
2. As an IDIR user, adjust supplier information so that they become a different size (i.e. by changing sales volume).
3. Login again as a supplier. You will see on the supplier info page, new size.
4. Go to the summary tab. You will the see the old size.

**Comment by shayjeff** [comment]
Closing ticket as: The BA will not modify sales/supplied numbers without notifying the BCeID user to update MY report by editing and reconfirming the pages. If the changes involve numbers from previous MY reports, the BCeID user will be instructed to create a supplementary report.
