### ISSUE TITLE
ZEVA: Update Tooltips for Credit Applications (BCeID User)

### ISSUE THREAD

**Issue by shayjeff** [bcgov/zeva#2365]
**Describe the task**
Implement a tooltip for the Credit Applications page for BCeID users. The tooltip will explain the terminology change from "Sales" to "Supplied," similar to the update for IDIR users.

**Purpose**
This task ensures BCeID users are provided with clear, consistent information about the change in terminology from “Sales” to “Supplied.” The tooltip will appear on both the Credit Applications Tab and Application Page.

**Acceptance Criteria**
- [ ] Add a tooltip next to the "Total Eligible ZEVs Supplied" column in the Credit Applications Tab with the text: “As of October 1st, 2024, total eligible ZEV sales converted to total eligible ZEVs supplied.”
- [ ] Add a tooltip to the "ZEVs Supplied" column in the Application Page with the same message.
- [ ] Ensure the tooltips display correctly and function as expected in both locations.

**Additional context**
- Mock-ups for both tooltips are provided:
   - [Credit Applications Tab Tooltip Mock-up](https://www.figma.com/proto/ijCyqDXXGVGDmmyfaXzPhk/ZEVA?page-id=50%3A193&node-id=985-246&node-type=frame&viewport=-1517%2C-1959%2C0.45&t=tIPzGMV4wvcaoXKr-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=985%3A246)
   - [Application Page Tooltip Mock-up](https://www.figma.com/proto/ijCyqDXXGVGDmmyfaXzPhk/ZEVA?page-id=50%3A193&node-id=985-75&node-type=frame&viewport=-1517%2C-1959%2C0.45&t=tIPzGMV4wvcaoXKr-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=985%3A246)

**Comment by tim738745** [comment]
This might help: https://www.npmjs.com/package/react-table-6#custom-cell-header-and-footer-rendering

**Comment by shayjeff** [comment]
Duplicate card
